MODULE Version

  IMPLICIT NONE

  CHARACTER(80), PARAMETER :: PROG_FULLNAME  = 'Parametric Hurricane Modeling System (PaHM)'
  CHARACTER(80), PARAMETER :: PROG_NAME      = 'PaHM'
  CHARACTER(80), PARAMETER :: PROG_NAME_LOW  = 'pahm'

  CHARACTER(10), PARAMETER :: PROG_DATE    = "12/16/2020"
  CHARACTER(10), PARAMETER :: PROG_VERSION = "1.0.0"
  INTEGER, PARAMETER       :: PROG_MAJOR   = 1
  INTEGER, PARAMETER       :: PROG_MINOR   = 0
  INTEGER, PARAMETER       :: PROG_PATCH   = 0

END MODULE VERSION
