PaHM: pahm_netcdfio Module Reference
pahm_netcdfio Module Reference
Data Types
type adcirccoorddata_t
type adcircvardata3d_t
type adcircvardata_t
type filedata_t
type timedata_t
Functions/Subroutines
subroutine initadcircnetcdfoutfile (adcircOutFile)
Initializes a new NetCDF data file and puts it in define mode.
subroutine newadcircnetcdfoutfile (ncID, adcircOutFile)
Creates a new NetCDF data file and puts it in define mode.
subroutine base_netcdfcheckerr (ierr, file, line)
Checks the return value from netCDF calls.
subroutine netcdfterminate ()
Terminates the program on NetCDF error.
subroutine writenetcdfrecord (adcircOutFile, timeLoc)
Writes data to the NetCDF file.
subroutine setrecordcounterandstoretime (ncID, f, t)
Sets the record counter.
Variables
integer, private ncformat
integer, parameter, private nc4form = IOR(NF90_NETCDF4, NF90_CLASSIC_MODEL)
integer, parameter, private nc3form = IOR(NF90_CLOBBER, 0)
integer, private nodedimid
integer, private vertdimid
integer, private elemdimid
integer, private meshdimid
integer, private meshvarid
integer, private projvarid
type(filedata_t), save myfile
type(timedata_t), save mytime
type(adcirccoorddata_t), save, private crdtime
type(adcirccoorddata_t), save, private crdlons
type(adcirccoorddata_t), save, private crdlats
type(adcirccoorddata_t), save, private crdxcs
type(adcirccoorddata_t), save, private crdycs
type(adcircvardata_t), save, private datelements
type(adcircvardata_t), save, private datatmpres
type(adcircvardata_t), save, private datwindx
type(adcircvardata_t), save, private datwindy
Function/Subroutine Documentation
base_netcdfcheckerr()
subroutine pahm_netcdfio::base_netcdfcheckerr (integer, intent(in) ierr, character(len=*), intent(in) file, integer, intent(in) line)
Checks the return value from netCDF calls.
Checks the return value from netCDF calls; if there was an error, it writes the error message to the screen and to the log file and then terminates the program.
Parameters
[in] ierr The error status from a NetCDF library call
[in] file The name of the file the error occured
[in] line The line number of the file the error occured
Definition at line 704 of file netcdfio.F90.
References pahm_messages::error, pahm_messages::info, netcdfterminate(), pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
initadcircnetcdfoutfile()
subroutine pahm_netcdfio::initadcircnetcdfoutfile (character(len=*), intent(inout) adcircOutFile)
Initializes a new NetCDF data file and puts it in define mode.
Initializes a new NetCDF data file and puts it in define mode. Sets up netCDF dimensions and variables.
Parameters
[in,out] adcircOutFile The name of the file to be initialized. The file is first created by calling NewAdcircNetCDFOutFile.
Definition at line 123 of file netcdfio.F90.
References pahm_mesh::agrid, crdlats, crdlons, crdtime, crdxcs, crdycs, datatmpres, datelements, timedateutils::datetime2string(), datwindx, datwindy, elemdimid, timedateutils::gettimeconvsec(), pahm_sizes::imissv, meshdimid, meshvarid, myfile, nc4form, pahm_global::ncdeflate, pahm_global::ncdlevel, ncformat, pahm_global::ncshuffle, pahm_global::ncvarnam_pres, pahm_global::ncvarnam_wndx, pahm_global::ncvarnam_wndy, pahm_mesh::ne, newadcircnetcdfoutfile(), pahm_mesh::nm, nodedimid, pahm_mesh::np, projvarid, pahm_global::rearth, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_sizes::rmissv, pahm_messages::setmessagesource(), pahm_mesh::sfea, pahm_mesh::sfea0, pahm_mesh::slam, pahm_mesh::slam0, pahm_global::times, pahm_global::title, pahm_global::unittime, pahm_messages::unsetmessagesource(), vertdimid, pahm_global::wpress, pahm_global::wvelx, pahm_global::wvely, pahm_mesh::xcslam, and pahm_mesh::ycsfea.
Referenced by pahm_drivermod::pahm_run().
netcdfterminate()
subroutine pahm_netcdfio::netcdfterminate
Terminates the program on NetCDF error.
Definition at line 740 of file netcdfio.F90.
References pahm_messages::info, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by base_netcdfcheckerr(), and newadcircnetcdfoutfile().
newadcircnetcdfoutfile()
subroutine pahm_netcdfio::newadcircnetcdfoutfile (integer, intent(out) ncID, character(len=*), intent(inout) adcircOutFile)
Creates a new NetCDF data file and puts it in define mode.
Creates a new NetCDF data file and puts it in define mode. The file extension is replaced by .nc or .nc4. If a file with the same name exists, it is renamed to: adcircOutFile.ext-YYYYMMDDhhmmss
Parameters
[out] ncID The NetCDF ID of the file to be created (output)
[in,out] adcircOutFile The name of the file to be created (input/output)
Definition at line 606 of file netcdfio.F90.
References pahm_messages::error, pahm_messages::info, nc3form, nc4form, ncformat, netcdfterminate(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by initadcircnetcdfoutfile().
setrecordcounterandstoretime()
subroutine pahm_netcdfio::setrecordcounterandstoretime (integer, intent(in) ncID, type(filedata_t), intent(inout) f, type(timedata_t), intent(inout) t)
Sets the record counter.
Compares the current simulation time with the array of output times in the file, and if the simulation time is before the end of the file, it sets the record counter to the right place within the existing data. Data that occur after the inserted data will remain, due to the inability of netcdf to delete data from files.
Parameters
[in] ncID The ID of the NetCDF file
[in,out] f The file structure
[in,out] t The time structure
Definition at line 850 of file netcdfio.F90.
References pahm_messages::info, pahm_messages::scratchformat, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
writenetcdfrecord()
subroutine pahm_netcdfio::writenetcdfrecord (character(len=*), intent(in) adcircOutFile, integer, intent(in) timeLoc)
Writes data to the NetCDF file.
This subroutine is called repeatedly to write the 2D field records in the NetCDF file.
Parameters
[in] adcircOutFile The name of the NetCDF file
[in] timeLoc The time record to write
Definition at line 775 of file netcdfio.F90.
References crdtime, datatmpres, datwindx, datwindy, timedateutils::gettimeconvsec(), nodedimid, pahm_messages::setmessagesource(), pahm_global::times, pahm_global::unittime, pahm_messages::unsetmessagesource(), pahm_global::wpress, pahm_global::wvelx, and pahm_global::wvely.
Referenced by pahm_drivermod::pahm_run().
Variable Documentation
crdlats
type(adcirccoorddata_t), save, private pahm_netcdfio::crdlats private
Definition at line 94 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
crdlons
type(adcirccoorddata_t), save, private pahm_netcdfio::crdlons private
Definition at line 93 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
crdtime
type(adcirccoorddata_t), save, private pahm_netcdfio::crdtime private
Definition at line 92 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and writenetcdfrecord().
crdxcs
type(adcirccoorddata_t), save, private pahm_netcdfio::crdxcs private
Definition at line 95 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
crdycs
type(adcirccoorddata_t), save, private pahm_netcdfio::crdycs private
Definition at line 96 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
datatmpres
type(adcircvardata_t), save, private pahm_netcdfio::datatmpres private
Definition at line 99 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and writenetcdfrecord().
datelements
type(adcircvardata_t), save, private pahm_netcdfio::datelements private
Definition at line 98 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
datwindx
type(adcircvardata_t), save, private pahm_netcdfio::datwindx private
Definition at line 100 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and writenetcdfrecord().
datwindy
type(adcircvardata_t), save, private pahm_netcdfio::datwindy private
Definition at line 101 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and writenetcdfrecord().
elemdimid
integer, private pahm_netcdfio::elemdimid private
Definition at line 36 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
meshdimid
integer, private pahm_netcdfio::meshdimid private
Definition at line 36 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
meshvarid
integer, private pahm_netcdfio::meshvarid private
Definition at line 37 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
myfile
type(filedata_t), save pahm_netcdfio::myfile private
Definition at line 89 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
mytime
type(timedata_t), save pahm_netcdfio::mytime
Definition at line 90 of file netcdfio.F90.
nc3form
integer, parameter, private pahm_netcdfio::nc3form = IOR(NF90_CLOBBER, 0) private
Definition at line 34 of file netcdfio.F90.
Referenced by newadcircnetcdfoutfile().
nc4form
integer, parameter, private pahm_netcdfio::nc4form = IOR(NF90_NETCDF4, NF90_CLASSIC_MODEL) private
Definition at line 33 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and newadcircnetcdfoutfile().
ncformat
integer, private pahm_netcdfio::ncformat private
Definition at line 32 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and newadcircnetcdfoutfile().
nodedimid
integer, private pahm_netcdfio::nodedimid private
Definition at line 36 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile(), and writenetcdfrecord().
projvarid
integer, private pahm_netcdfio::projvarid private
Definition at line 37 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().
vertdimid
integer, private pahm_netcdfio::vertdimid private
Definition at line 36 of file netcdfio.F90.
Referenced by initadcircnetcdfoutfile().