PaHM: timedateutils::splitdatetimestring Interface Reference
timedateutils::splitdatetimestring Interface Reference
Public Member Functions
subroutine splitdatetimestring (inDateTime, iYear, iMonth, iDay, iHour, iMin, iSec)
Splits a date string into components.
subroutine splitdatetimestring2 (inDateTime, iDate, iTime)
Splits a date string into two components.
Detailed Description
Definition at line 37 of file timedateutils.F90.
Constructor & Destructor Documentation
splitdatetimestring()
subroutine timedateutils::splitdatetimestring::splitdatetimestring (character(len=*), intent(in) inDateTime, integer, intent(out) iYear, integer, intent(out) iMonth, integer, intent(out) iDay, integer, intent(out) iHour, integer, intent(out) iMin, integer, intent(out) iSec)
Splits a date string into components.
This subroutine splits the string inDate (YYYYMMDDhhmmss) in six integers that is, "iYear (YYYY)", "iMonth (MM)", "iDay (DD)", "iHour (hh)", "iMin (mm)" and "iSec (ss)".
Parameters
inDateTime The input date string: YYYYMMDDhhmmss
iYear The year (YYYY, integer, 1582 <= YYYY, output)
iMonth The month of the year (MM, integer, 1 <= MM <=12, output)
iDay The day of the month (DD, integer, 1 <= DD <=31, output)
iHour The hour of the day (hh, integer, 0 <= hh <= 23, output)
iMin The minute of the hour (mm, integer, 0 <= mm <= 59, output)
iSec The second of the minute (ss, integer, 0 <= ss <= 59, output)
Definition at line 1073 of file timedateutils.F90.
References timedateutils::monthdays(), and timedateutils::preprocessdatetimestring().
Member Function/Subroutine Documentation
splitdatetimestring2()
subroutine timedateutils::splitdatetimestring::splitdatetimestring2 (character(len=*), intent(in) inDateTime, integer, intent(out) iDate, integer, intent(out) iTime)
Splits a date string into two components.
This subroutine splits the string inDate (YYYYMMDDhhmmss) in two integers that is, "iDate (YYYYMMDD)" and "iTime (hhmmss)".
Parameters
inDateTime The input date string: YYYYMMDDhhmmss
iDate The integer date (YYYYMMDD, output)
iTime The integer time (hhmmss, output)
Definition at line 1141 of file timedateutils.F90.
References timedateutils::joindate().
The documentation for this interface was generated from the following file:
timedateutils.F90