PaHM: pahm_mesh Module Reference
pahm_mesh Module Reference
Functions/Subroutines
subroutine readmesh ()
Reads an input mesh file for the specified supported model type.
subroutine readmeshasciifort14 ()
Reads the ADCIRC fort.14 mesh file.
subroutine allocatenodalandelementalarrays ()
Allocates memory to mesh arrays.
Variables
character(len=80) agrid
integer np = IMISSV
integer ne = IMISSV
integer ics
real(sz), dimension(:), allocatable dp
integer, dimension(:), allocatable nfn
integer, dimension(:, :), allocatable nm
real(sz), dimension(:), allocatable slam
real(sz), dimension(:), allocatable sfea
real(sz), dimension(:), allocatable xcslam
real(sz), dimension(:), allocatable ycsfea
real(sz) slam0 = RMISSV
real(sz) sfea0 = RMISSV
integer, parameter maxfacenodes = 5
logical ismeshok = .FALSE.
Function/Subroutine Documentation
allocatenodalandelementalarrays()
subroutine pahm_mesh::allocatenodalandelementalarrays
Allocates memory to mesh arrays.
Mesh related memory allocation for any array that is dimensioned by the number of nodes in the mesh or the number of elements in the mesh.
Definition at line 301 of file mesh.F90.
References dp, maxfacenodes, ne, nfn, nm, np, sfea, slam, xcslam, and ycsfea.
Referenced by readmeshasciifort14().
readmesh()
subroutine pahm_mesh::readmesh
Reads an input mesh file for the specified supported model type.
Read the mesh file for the specified model type (meshFileType) and in ASCII or NetCDF format (if applicable).
Definition at line 69 of file mesh.F90.
References pahm_messages::error, pahm_global::meshfileform, pahm_global::meshfilename, pahm_global::meshfilenamespecified, pahm_global::meshfiletype, readmeshasciifort14(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::terminate(), utilities::touppercase(), and pahm_messages::unsetmessagesource().
Referenced by pahm_drivermod::pahm_init().
readmeshasciifort14()
subroutine pahm_mesh::readmeshasciifort14
Reads the ADCIRC fort.14 mesh file.
Reads the ADCIRC fort.14 mesh file and sets all mesh variables and arrays.
Definition at line 170 of file mesh.F90.
References agrid, allocatenodalandelementalarrays(), pahm_messages::info, ismeshok, pahm_global::lun_inp, maxfacenodes, pahm_global::meshfilename, ne, np, utilities::openfileforread(), pahm_messages::setmessagesource(), sfea, sfea0, slam, slam0, xcslam, and ycsfea.
Referenced by readmesh().
Variable Documentation
agrid
character(len=80) pahm_mesh::agrid
Definition at line 32 of file mesh.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
dp
real(sz), dimension(:), allocatable pahm_mesh::dp
Definition at line 36 of file mesh.F90.
Referenced by allocatenodalandelementalarrays().
ics
integer pahm_mesh::ics
Definition at line 35 of file mesh.F90.
ismeshok
logical pahm_mesh::ismeshok = .FALSE.
Definition at line 51 of file mesh.F90.
Referenced by parwind::gethollandfields(), and readmeshasciifort14().
maxfacenodes
integer, parameter pahm_mesh::maxfacenodes = 5
Definition at line 48 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), and readmeshasciifort14().
ne
integer pahm_mesh::ne = IMISSV
Definition at line 34 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
nfn
integer, dimension(:), allocatable pahm_mesh::nfn
Definition at line 37 of file mesh.F90.
Referenced by allocatenodalandelementalarrays().
nm
integer, dimension(:, :), allocatable pahm_mesh::nm
Definition at line 38 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), and pahm_netcdfio::initadcircnetcdfoutfile().
np
integer pahm_mesh::np = IMISSV
Definition at line 33 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
sfea
real(sz), dimension(:), allocatable pahm_mesh::sfea
Definition at line 40 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
sfea0
real(sz) pahm_mesh::sfea0 = RMISSV
Definition at line 45 of file mesh.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
slam
real(sz), dimension(:), allocatable pahm_mesh::slam
Definition at line 39 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
slam0
real(sz) pahm_mesh::slam0 = RMISSV
Definition at line 44 of file mesh.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
xcslam
real(sz), dimension(:), allocatable pahm_mesh::xcslam
Definition at line 41 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().
ycsfea
real(sz), dimension(:), allocatable pahm_mesh::ycsfea
Definition at line 42 of file mesh.F90.
Referenced by allocatenodalandelementalarrays(), parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and readmeshasciifort14().