PaHM: pahm_drivermod Module Reference
pahm_drivermod Module Reference
Functions/Subroutines
subroutine getprogramcmdlargs ()
Prints on the screen the help system of the PaHM program.
subroutine pahm_init ()
Subroutine to initialize a PaHM run.
subroutine pahm_run (nTimeSTP)
Subroutine to run PaHM (timestepping).
subroutine pahm_finalize ()
Subroutine to finalize a PaHM run.
Variables
integer, save cnttimebegin
integer, save cnttimeend
Function/Subroutine Documentation
getprogramcmdlargs()
subroutine pahm_drivermod::getprogramcmdlargs
Prints on the screen the help system of the PaHM program.
Definition at line 40 of file driver_mod.F90.
References pahm_global::controlfilename, pahm_messages::initlogging(), pahm_messages::programhelp(), pahm_messages::programversion(), and utilities::readcontrolfile().
Referenced by pahm_init().
pahm_finalize()
subroutine pahm_drivermod::pahm_finalize
Subroutine to finalize a PaHM run.
Definition at line 194 of file driver_mod.F90.
References pahm_messages::closelogfile(), pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by pahm().
pahm_init()
subroutine pahm_drivermod::pahm_init
Subroutine to initialize a PaHM run.
Definition at line 94 of file driver_mod.F90.
References cnttimebegin, cnttimeend, getprogramcmdlargs(), pahm_messages::initlogging(), pahm_global::noutdt, parwind::readcsvbesttrackfile(), pahm_mesh::readmesh(), pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by pahm().
pahm_run()
subroutine pahm_drivermod::pahm_run (integer, intent(in), optional nTimeSTP)
Subroutine to run PaHM (timestepping).
Definition at line 136 of file driver_mod.F90.
References cnttimebegin, cnttimeend, pahm_messages::error, parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), pahm_global::modeltype, pahm_global::outfilename, pahm_global::outfilenamespecified, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_global::times, pahm_messages::unsetmessagesource(), pahm_global::wpress, pahm_netcdfio::writenetcdfrecord(), pahm_global::wvelx, and pahm_global::wvely.
Referenced by pahm().
Variable Documentation
cnttimebegin
integer, save pahm_drivermod::cnttimebegin
Definition at line 23 of file driver_mod.F90.
Referenced by pahm_init(), and pahm_run().
cnttimeend
integer, save pahm_drivermod::cnttimeend
Definition at line 23 of file driver_mod.F90.
Referenced by pahm_init(), and pahm_run().