PaHM: pahm.F90 File Reference
pahm.F90 File Reference
Main PaHM program, calls Init, Run and Finalize procedures.
Functions/Subroutines
program pahm
Detailed Description
Main PaHM program, calls Init, Run and Finalize procedures.
1) Initialize PaHM by establishing the logging facilities and calling the subroutine "GetProgramCmdlArgs" to get possible command line arguments and set the defaults. During the initialization stage, PaHM reads the mandatory input control file (defaults to pahm_control.in) to read in the definitions of different variables used in PaHM. At this stage we read the mesh/grid of the domain or the generic mesh/grid input file and the list of best track files supplied by the user.
2) Start the PaHM run (timestepping).
3) Finalize the PaHM run and exit the program.
Author
Panagiotis Velissariou panag.nosp@m.ioti.nosp@m.s.vel.nosp@m.issa.nosp@m.riou@.nosp@m.noaa.nosp@m..gov
Definition in file pahm.F90.
Function/Subroutine Documentation
pahm()
program pahm
Definition at line 26 of file pahm.F90.
References pahm_drivermod::pahm_finalize(), pahm_drivermod::pahm_init(), and pahm_drivermod::pahm_run().