PaHM: sortutils.F90 File Reference
sortutils.F90 File Reference
Data Types
interface sortutils::indexx
interface sortutils::arth
interface sortutils::arraycopy
interface sortutils::arrayequal
interface sortutils::swap
Modules
module sortutils
Functions/Subroutines
subroutine sortutils::indexxint (arr1D, idx1D, status)
Indexes a 1D integer array in ascending order.
subroutine icompxchg (i, j)
subroutine sortutils::indexxint8 (arr1D, idx1D, status)
Indexes a 1D 32-bit integer array in ascending order.
subroutine sortutils::indexxstring (arr1D, idx1D, status, caseSens)
Indexes a 1D string array in ascending order.
subroutine sortutils::indexxsingle (arr1D, idx1D, status)
Indexes a 1D single precision array in ascending order.
subroutine sortutils::indexxdouble (arr1D, idx1D, status)
Indexes a 1D double precision array in ascending order.
subroutine sortutils::quicksort (arr1D, status)
Sorts the array arr1D into ascending numerical order using Quicksort.
subroutine sortutils::sort2 (arr1D, slv1D, status)
Sorts two 1D arrays into ascending numerical order using Quicksort.
subroutine sortutils::arraycopyint (src, dest, nCP, nNCP)
Copies the 1D source integer array "src" into the 1D destination array "dest".
subroutine sortutils::arraycopysingle (src, dest, nCP, nNCP)
Copies the 1D source single precision array "src" into the 1D destination array "dest".
subroutine sortutils::arraycopydouble (src, dest, nCP, nNCP)
Copies the 1D source double precision array "src" into the 1D destination array "dest".
logical function sortutils::arrayequalint (arr1, arr2)
Compares two one-dimensional integer arrays for equality.
logical function sortutils::arrayequalsingle (arr1, arr2)
Compares two one-dimensional single precision arrays for equality.
logical function sortutils::arrayequaldouble (arr1, arr2)
Compares two one-dimensional double precision arrays for equality.
integer function sortutils::stringlexcomp (str1, str2, mSensitive)
Performs a lexical comparison between two strings.
subroutine sortutils::swapint (a, b, mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
subroutine sortutils::swapsingle (a, b, mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
subroutine sortutils::swapdouble (a, b, mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
subroutine sortutils::swapintvec (a, b, mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
subroutine sortutils::swapsinglevec (a, b, mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
subroutine sortutils::swapdoublevec (a, b, mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
pure integer function, dimension(n) sortutils::arthint (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
pure real(sp) function, dimension(n) sortutils::arthsingle (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
pure real(hp) function, dimension(n) sortutils::arthdouble (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
Detailed Description
Author
Panagiotis Velissariou panag.nosp@m.ioti.nosp@m.s.vel.nosp@m.issa.nosp@m.riou@.nosp@m.noaa.nosp@m..gov
Definition in file sortutils.F90.
Function/Subroutine Documentation
icompxchg()
subroutine icompxchg (integer, intent(inout) i, integer, intent(inout) j)
Definition at line 214 of file sortutils.F90.
Referenced by sortutils::indexx::indexxdouble(), sortutils::indexx::indexxint(), sortutils::indexx::indexxint8(), sortutils::indexx::indexxsingle(), and sortutils::indexx::indexxstring().