PaHM: pahm_vortex Module Reference
pahm_vortex Module Reference
Functions/Subroutines
subroutine, public calcintensitychange (var, times, calcInt, status, order)
This subroutine calculates the intensity time change of a variable using second order mumerical accuracy and uneven spacing.
subroutine, public uvtrans (lat, lon, times, u, v, status, order)
This subroutine calculates the translational velocity of a moving hurricane using second order mumerical accuracy and uneven spacing.
subroutine, public uvtranspoint (lat1, lon1, lat2, lon2, time1, time2, u, v)
This subroutine calculates the translational velocity of a moving hurricane.
subroutine, public newvortex (pinf, p0, lat, lon, vm)
Creates a new Vortex object.
subroutine, public newvortexfull (pinf, p0, lat, lon, vm)
Creates a new Vortex object.
subroutine, public setvortex (pinf, p0, lat, lon)
Sets basic parameters for a new Vortex object.
subroutine, public setrmaxes (rMaxW)
subroutine, public getrmaxes (rMaxW)
subroutine, public calcrmaxes ()
Calculates the radius of maximum winds for all storm quadrants.
subroutine, public calcrmaxesfull ()
Calculates the radius of maximum winds for all storm quadrants.
subroutine, public fitrmaxes ()
Calculates the coefficients that fit the given radius of maximum winds for all storm quadrants.
subroutine, public fitrmaxes4 ()
subroutine, public setvmaxesbl (vMaxW)
subroutine, public getvmaxesbl (vMaxW)
subroutine, public setusevmaxesbl (u)
subroutine, public setshapeparameter (param)
real(sz) function, public getshapeparameter ()
real(sz) function, dimension(4), public getshapeparameters ()
real(sz) function, dimension(4), public getphifactors ()
subroutine, public setisotachradii (ir)
subroutine, public setisotachwindspeeds (vrQ)
subroutine, public setisotachwindspeed (sp)
subroutine, public setusequadrantvr (u)
logical function, public getusequadrantvr ()
real(sz) function, public spinterp (angle, dist, opt)
Spatial Interpolation function based on angle and r.
real(sz) function, public interpr (quadVal, quadSel, quadDis)
real(sz) function, public rmw (angle)
Calculate the radius of maximum winds.
subroutine, public uvp (lat, lon, uTrans, vTrans, u, v, p)
Calculates (u, v) wind components and surface pressure from an asymmetric hurricane wind model.
subroutine, public uvpr (iDist, iAngle, iRmx, iRmxTrue, iB, iVm, iPhi, uTrans, vTrans, geof, u, v, p)
Calculates (u, v) wind components and surface pressure from an asymmetric hurricane wind model.
real(sz) function, public fang (r, rmx)
Compute a wind angle to parameterize frictional inflow across isobars.
subroutine rotate (x, y, angle, whichWay, xr, yr)
Rotate a 2D vector (x, y) by an angle.
real(sz) function, public getlatestrmax ()
real(sz) function, public getlatestangle ()
real(sz) function vhwithcorifull (testRMax)
External function f(x) = 0 for which a root is sought using Brent's root-finding method.
real(sz) function vhwithcori (testRMax)
External function f(x) = 0 for which a root is sought using Brent's root-finding method.
real(sz) function vhnocori (testRMax)
real(sz) function findroot (func, x1, x2, dx, a, b)
Use brute-force marching to find a root the interval [x1,x2].
Variables
integer, parameter nquads = 4
integer, parameter npoints = NQUADS + 2
real(sz), dimension(npoints) rmaxes
real(sz), dimension(npoints, 4), public rmaxes4
real(sz) pn
real(sz) pc
real(sz) clat
real(sz) clon
real(sz) vmax
real(sz) b
real(sz) corio
real(sz) vr
real(sz) phi
real(sz), dimension(npoints) phis
real(sz), dimension(npoints, 4) phis4
real(sz), dimension(npoints) bs
real(sz), dimension(npoints, 4), public bs4
real(sz), dimension(npoints) vmbl
real(sz), dimension(npoints, 4), public vmbl4
integer, dimension(npoints, 4), public quadflag4
real(sz), dimension(npoints, 4), public quadir4
real(sz), dimension(nquads) vrquadrant
real(sz), dimension(nquads) radius
integer quad
real(sz) latestrmax
real(sz) latestangle
logical usequadrantvr
logical usevmaxesbl
Function/Subroutine Documentation
calcintensitychange()
subroutine, public pahm_vortex::calcintensitychange (real(sz), dimension(:), intent(in) var, real(sz), dimension(:), intent(in) times, real(sz), dimension(:), intent(out) calcInt, integer, intent(out) status, integer, intent(in), optional order)
This subroutine calculates the intensity time change of a variable using second order mumerical accuracy and uneven spacing.
Parameters
[in] var The input variable (vector)
[in] times Time values (vector) at the center locations
[out] calcInt The calculated intensity change (df/dt)
[out] status Error status (0 means no error)
[in] order The accuracy order required for the calculations (1, 2)
   order   <= 1: first order approximation for finite differences
   order   >= 2: second order approximation for finite differences
Definition at line 108 of file vortex.F90.
References pahm_global::deg2rad, pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_global::times, and pahm_messages::unsetmessagesource().
Referenced by parwind::processhollanddata().
calcrmaxes()
subroutine, public pahm_vortex::calcrmaxes
Calculates the radius of maximum winds for all storm quadrants.
Calculates rMax, the radius of maximum winds (nm) in all quadrants, plus 2 extra values to tie down circular periodicity
Definition at line 743 of file vortex.F90.
References b, bs, findroot(), nquads, quad, radius, rmaxes, vhnocori(), vhwithcori(), vmax, and vmbl.
Referenced by parwind::processasymmetricvortexdata().
calcrmaxesfull()
subroutine, public pahm_vortex::calcrmaxesfull
Calculates the radius of maximum winds for all storm quadrants.
Solves the full gradient wind equation without the assumption of cyclostrohpic balance. Calculates rMax, the radius of maximum winds (nm) in all quadrants, plus 2 extra values to tie down circular periodicity.
Definition at line 823 of file vortex.F90.
References b, bs, corio, findroot(), pahm_global::kt2ms, pahm_global::mb2pa, pahm_global::nm2m, nquads, pc, phi, phis, pn, quad, radius, pahm_global::rhoair, rmaxes, vhwithcorifull(), vmax, and vmbl.
Referenced by parwind::processasymmetricvortexdata().
fang()
real(sz) function, public pahm_vortex::fang (real(sz), intent(in) r, real(sz), intent(in) rmx)
Compute a wind angle to parameterize frictional inflow across isobars.
Parameters
[in] r Distance from center of storm
[in] rmx Radius of maximum winds
Returns
myValOut Frictional inflow angle (degrees)
Definition at line 1742 of file vortex.F90.
Referenced by parwind::processasymmetricvortexdata(), uvp(), and uvpr().
findroot()
real(sz) function pahm_vortex::findroot (real(sz), external func, real(sz), intent(in) x1, real(sz), intent(in) x2, real(sz), intent(in) dx, real(sz), intent(out) a, real(sz), intent(out) b)
Use brute-force marching to find a root the interval [x1,x2].
Parameters
[in] func Function f(x)=0 for which root is sought
[in] x1 Left side of the interval
[in] x2 Right side of the interval
[in] dx x increment for march
[out] a Left side of interval that brackets the root
[out] b Right side of interval that brackets the root
Returns
myRoot The value of the root
Definition at line 2006 of file vortex.F90.
References b.
Referenced by calcrmaxes(), and calcrmaxesfull().
fitrmaxes()
subroutine, public pahm_vortex::fitrmaxes
Calculates the coefficients that fit the given radius of maximum winds for all storm quadrants.
Generates 2 additional (theta, rMax) points for curve fitting.
Definition at line 956 of file vortex.F90.
References rmaxes.
fitrmaxes4()
subroutine, public pahm_vortex::fitrmaxes4
Definition at line 971 of file vortex.F90.
References bs4, phis4, quadflag4, quadir4, rmaxes4, and vmbl4.
Referenced by parwind::getgahmfields().
getlatestangle()
real(sz) function, public pahm_vortex::getlatestangle
Definition at line 1838 of file vortex.F90.
References latestangle.
getlatestrmax()
real(sz) function, public pahm_vortex::getlatestrmax
Definition at line 1825 of file vortex.F90.
References latestrmax.
getphifactors()
real(sz) function, dimension(4), public pahm_vortex::getphifactors
Definition at line 1103 of file vortex.F90.
References phis.
Referenced by parwind::processasymmetricvortexdata().
getrmaxes()
subroutine, public pahm_vortex::getrmaxes (real(sz), dimension(4), intent(out) rMaxW)
Definition at line 715 of file vortex.F90.
References rmaxes.
Referenced by parwind::processasymmetricvortexdata().
getshapeparameter()
real(sz) function, public pahm_vortex::getshapeparameter
Definition at line 1067 of file vortex.F90.
References b.
Referenced by parwind::processasymmetricvortexdata().
getshapeparameters()
real(sz) function, dimension(4), public pahm_vortex::getshapeparameters
Definition at line 1082 of file vortex.F90.
References bs.
Referenced by parwind::processasymmetricvortexdata().
getusequadrantvr()
logical function, public pahm_vortex::getusequadrantvr
Definition at line 1184 of file vortex.F90.
References usequadrantvr.
Referenced by vhnocori(), vhwithcori(), and vhwithcorifull().
getvmaxesbl()
subroutine, public pahm_vortex::getvmaxesbl (real(sz), dimension(4), intent(out) vMaxW)
Definition at line 1020 of file vortex.F90.
References vmbl.
Referenced by parwind::processasymmetricvortexdata().
interpr()
real(sz) function, public pahm_vortex::interpr (real(sz), dimension(npoints, 4), intent(in) quadVal, integer, intent(in) quadSel, real(sz), intent(in) quadDis)
Definition at line 1283 of file vortex.F90.
References quadflag4, and quadir4.
Referenced by spinterp().
newvortex()
subroutine, public pahm_vortex::newvortex (real(sz), intent(in) pinf, real(sz), intent(in) p0, real(sz), intent(in) lat, real(sz), intent(in) lon, real(sz), intent(in) vm)
Creates a new Vortex object.
A new vortex is created with the essential parameters calculated.
Parameters
[in] pinf Ambient surface pressure (mb)
[in] p0 Surface pressure at center of storm (mb)
[in] lat Latitude of storm center (degrees north)
[in] lon Longitude of storm center (degrees east)
[in] vm Max sustained wind velocity in storm (knots)
Definition at line 563 of file vortex.F90.
References b, bs, clat, clon, corio, pahm_global::deg2rad, pahm_global::kt2ms, pahm_global::mb2pa, pahm_global::omega, pc, pn, pahm_global::rhoair, vmax, and vmbl.
newvortexfull()
subroutine, public pahm_vortex::newvortexfull (real(sz), intent(in) pinf, real(sz), intent(in) p0, real(sz), intent(in) lat, real(sz), intent(in) lon, real(sz), intent(in) vm)
Creates a new Vortex object.
A new vortex is created for the full gradient wind balance.
Parameters
[in] pinf Ambient surface pressure (mb)
[in] p0 Surface pressure at center of storm (mb)
[in] lat Latitude of storm center (degrees north)
[in] lon Longitude of storm center (degrees east)
[in] vm Max sustained wind velocity in storm (knots)
Definition at line 617 of file vortex.F90.
References b, bs, clat, clon, corio, pahm_global::deg2rad, pahm_global::kt2ms, pahm_global::mb2pa, pahm_global::omega, pc, phi, phis, pn, pahm_global::rhoair, vmax, and vmbl.
Referenced by parwind::processasymmetricvortexdata().
rmw()
real(sz) function, public pahm_vortex::rmw (real(sz), intent(in) angle)
Calculate the radius of maximum winds.
Parameters
[in] angle Azimuthal angle (degrees)
Returns
myValOut Rmw: Radius of maximum winds (meters) from curve fit
Definition at line 1362 of file vortex.F90.
References rmaxes.
Referenced by uvp().
rotate()
subroutine pahm_vortex::rotate (real(sz), intent(in) x, real(sz), intent(in) y, real(sz), intent(in) angle, real(sz), intent(in) whichWay, real(sz), intent(out) xr, real(sz), intent(out) yr) private
Rotate a 2D vector (x, y) by an angle.
Parameters
[in] x x component of vector
[in] y y component of vector
[in] angle Angle to rotate the vector (degrees)
[in] whichWay direction of the rotation
   whichWay  < 0: clockwise
   whichWay  > 0: counter-clockwise
[out] xr x component of rotated vector
[out] yr y component of rotated vector
Definition at line 1795 of file vortex.F90.
References pahm_global::deg2rad.
Referenced by uvp(), and uvpr().
setisotachradii()
subroutine, public pahm_vortex::setisotachradii (real(sz), dimension(4), intent(in) ir)
Definition at line 1124 of file vortex.F90.
References radius.
Referenced by parwind::processasymmetricvortexdata().
setisotachwindspeed()
subroutine, public pahm_vortex::setisotachwindspeed (real(sz), intent(in) sp)
Definition at line 1154 of file vortex.F90.
References vr.
setisotachwindspeeds()
subroutine, public pahm_vortex::setisotachwindspeeds (real(sz), dimension(4), intent(in) vrQ)
Definition at line 1139 of file vortex.F90.
References vrquadrant.
Referenced by parwind::processasymmetricvortexdata().
setrmaxes()
subroutine, public pahm_vortex::setrmaxes (real(sz), dimension(4), intent(in) rMaxW)
Definition at line 697 of file vortex.F90.
References rmaxes.
setshapeparameter()
subroutine, public pahm_vortex::setshapeparameter (real(sz) param)
Definition at line 1052 of file vortex.F90.
References b.
setusequadrantvr()
subroutine, public pahm_vortex::setusequadrantvr (logical, intent(in) u)
Definition at line 1169 of file vortex.F90.
References usequadrantvr.
Referenced by parwind::processasymmetricvortexdata().
setusevmaxesbl()
subroutine, public pahm_vortex::setusevmaxesbl (logical, intent(in) u)
Definition at line 1039 of file vortex.F90.
References usevmaxesbl.
Referenced by parwind::processasymmetricvortexdata().
setvmaxesbl()
subroutine, public pahm_vortex::setvmaxesbl (real(sz), dimension(4), intent(in) vMaxW)
Definition at line 1001 of file vortex.F90.
References vmbl.
Referenced by parwind::processasymmetricvortexdata().
setvortex()
subroutine, public pahm_vortex::setvortex (real(sz), intent(in) pinf, real(sz), intent(in) p0, real(sz), intent(in) lat, real(sz), intent(in) lon)
Sets basic parameters for a new Vortex object.
Aim is to define pn, pc, and corio.
Parameters
[in] pinf Hurricane Ambient pressure (mb)
[in] p0 Hurricane central pressure (mb)
[in] lat Latitude of storm center (degrees north)
[in] lon Longitude of storm center (degrees east)
Definition at line 670 of file vortex.F90.
References clat, clon, corio, pahm_global::deg2rad, pahm_global::omega, pc, and pn.
Referenced by parwind::getgahmfields().
spinterp()
real(sz) function, public pahm_vortex::spinterp (real(sz), intent(in) angle, real(sz), intent(in) dist, integer, intent(in) opt)
Spatial Interpolation function based on angle and r.
Aim is to define pn, pc, and corio.
Parameters
[in] angle Azimuthal angle (degrees)
[in] dist Distnace to storm Center (nm)
[in] opt Flag to calculate one of rMax/vMax/B
Returns
myValOut The interpolated value for rMax/vMax/B
Definition at line 1222 of file vortex.F90.
References bs4, interpr(), rmaxes4, and vmbl4.
Referenced by parwind::getgahmfields().
uvp()
subroutine, public pahm_vortex::uvp (real(sz), intent(in) lat, real(sz), intent(in) lon, real(sz), intent(in) uTrans, real(sz), intent(in) vTrans, real(sz), intent(out) u, real(sz), intent(out) v, real(sz), intent(out) p)
Calculates (u, v) wind components and surface pressure from an asymmetric hurricane wind model.
Parameters
[in] lat Latitude of nodal point (degrees north)
[in] lon Longitude of nodal point (degrees east)
[in] uTrans x component of translational velocity (knts)
[in] vTrans y component of translational velocity (knts)
[out] u x component of wind velocity at nodal point (m/s)
[out] v y component of wind velocity at nodal point (m/s)
[out] p Surface pressure at nodal point (Pa)
Definition at line 1441 of file vortex.F90.
References b, clat, clon, corio, pahm_global::deg2rad, fang(), pahm_global::kt2ms, latestangle, latestrmax, pahm_global::m2nm, pahm_global::mb2pa, pahm_global::nm2m, pahm_global::one2ten, pc, pn, pahm_global::rad2deg, pahm_global::rearth, rmw(), rotate(), vmax, and pahm_global::windreduction.
uvpr()
subroutine, public pahm_vortex::uvpr (real(sz), intent(in) iDist, real(sz), intent(in) iAngle, real(sz), intent(in) iRmx, real(sz), intent(in) iRmxTrue, real(sz), intent(in) iB, real(sz), intent(in) iVm, real(sz), intent(in) iPhi, real(sz), intent(in) uTrans, real(sz), intent(in) vTrans, integer, intent(in) geof, real(sz), intent(out) u, real(sz), intent(out) v, real(sz), intent(out) p)
Calculates (u, v) wind components and surface pressure from an asymmetric hurricane wind model.
Parameters
[in] iDist Distance to hurricane center in nautical miles
[in] iAngle Azimuthal angle (degrees)
[in] iRmx Radius of maximum wind (Rmw)
[in] iRmxTrue
[in] iB Holland B parameter
[in] iVm Vortex maximum velocity at upper boundary
[in] iPhi Vortex correction factor
[in] uTrans x component of translational velocity (knts)
[in] vTrans y component of translational velocity (knts)
[in] geof Factor to calculate wind parameters from the asymmetric hurricane vortex (geof = 1)
[out] u x component of wind velocity at nodal point (m/s)
[out] v y component of wind velocity at nodal point (m/s)
[out] p Surface pressure at nodal point (Pa)
Definition at line 1608 of file vortex.F90.
References b, clat, corio, pahm_global::deg2rad, fang(), pahm_global::kt2ms, pahm_global::mb2pa, pahm_global::nm2m, pahm_global::one2ten, pc, phi, pn, rotate(), vmax, and pahm_global::windreduction.
Referenced by parwind::getgahmfields().
uvtrans()
subroutine, public pahm_vortex::uvtrans (real(sz), dimension(:), intent(in) lat, real(sz), dimension(:), intent(in) lon, real(sz), dimension(:), intent(in) times, real(sz), dimension(:), intent(out) u, real(sz), dimension(:), intent(out) v, integer, intent(out) status, integer, intent(in), optional order)
This subroutine calculates the translational velocity of a moving hurricane using second order mumerical accuracy and uneven spacing.
Parameters
[in] lat Latitude values (vector) of the center (degrees north)
[in] lon Longitude values (vector) of the center (degrees east)
[in] times Time values (vector) at the center locations (seconds)
[out] u x component of the translational velocities (m/s)
[out] v y component of the translational velocities (m/s)
[out] status Error status (0 means no error)
[in] order The accuracy order required for the calculations (1, 2)
   order   <= 1: first order approximation for finite differences
   order   >= 2: second order approximation for finite differences
Definition at line 282 of file vortex.F90.
References pahm_global::deg2rad, pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_global::times, and pahm_messages::unsetmessagesource().
Referenced by parwind::processhollanddata().
uvtranspoint()
subroutine, public pahm_vortex::uvtranspoint (real(sz), intent(in) lat1, real(sz), intent(in) lon1, real(sz), intent(in) lat2, real(sz), intent(in) lon2, real(sz), intent(in) time1, real(sz), intent(in) time2, real(sz), intent(out) u, real(sz), intent(out) v)
This subroutine calculates the translational velocity of a moving hurricane.
Parameters
[in] lat1 Previous latitude of center (degrees north)
[in] lon1 Previous longitude of center (degrees east)
[in] lat2 Current latitude of center (degrees north)
[in] lon2 Current longitude of center (degrees east)
[in] time1 Previous time (seconds)
[out] time2 Current time (seconds)
[out] u x component of translational velocity (m/s)
[out] v y component of translational velocity (m/s)
Definition at line 509 of file vortex.F90.
References pahm_global::deg2rad.
Referenced by parwind::processasymmetricvortexdata().
vhnocori()
real(sz) function pahm_vortex::vhnocori (real(sz), intent(in) testRMax)
Definition at line 1954 of file vortex.F90.
References b, getusequadrantvr(), pahm_global::kt2ms, pahm_global::ms2kt, quad, radius, vmax, vr, and vrquadrant.
Referenced by calcrmaxes().
vhwithcori()
real(sz) function pahm_vortex::vhwithcori (real(sz), intent(in) testRMax)
External function f(x) = 0 for which a root is sought using Brent's root-finding method.
Parameters
[in] testRMax Iterative values which converge to root
Returns
myValOut The function's result
Definition at line 1918 of file vortex.F90.
References b, corio, getusequadrantvr(), pahm_global::kt2ms, pahm_global::ms2kt, pahm_global::nm2m, quad, radius, vmax, vr, and vrquadrant.
Referenced by calcrmaxes().
vhwithcorifull()
real(sz) function pahm_vortex::vhwithcorifull (real(sz), intent(in) testRMax) private
External function f(x) = 0 for which a root is sought using Brent's root-finding method.
Parameters
[in] testRMax Iterative values which converge to root
Returns
myValOut The function's result
Definition at line 1866 of file vortex.F90.
References b, corio, getusequadrantvr(), pahm_global::kt2ms, pahm_global::ms2kt, pahm_global::nm2m, phi, quad, radius, vmax, vr, and vrquadrant.
Referenced by calcrmaxesfull().
Variable Documentation
b
real(sz) pahm_vortex::b private
Definition at line 54 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), findroot(), getshapeparameter(), newvortex(), newvortexfull(), setshapeparameter(), uvp(), uvpr(), vhnocori(), vhwithcori(), and vhwithcorifull().
bs
real(sz), dimension(npoints) pahm_vortex::bs private
Definition at line 61 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), getshapeparameters(), newvortex(), and newvortexfull().
bs4
real(sz), dimension(npoints, 4), public pahm_vortex::bs4
Definition at line 62 of file vortex.F90.
Referenced by fitrmaxes4(), parwind::getgahmfields(), and spinterp().
clat
real(sz) pahm_vortex::clat private
Definition at line 50 of file vortex.F90.
Referenced by newvortex(), newvortexfull(), setvortex(), uvp(), and uvpr().
clon
real(sz) pahm_vortex::clon private
Definition at line 51 of file vortex.F90.
Referenced by newvortex(), newvortexfull(), setvortex(), and uvp().
corio
real(sz) pahm_vortex::corio private
Definition at line 55 of file vortex.F90.
Referenced by calcrmaxesfull(), newvortex(), newvortexfull(), setvortex(), uvp(), uvpr(), vhwithcori(), and vhwithcorifull().
latestangle
real(sz) pahm_vortex::latestangle private
Definition at line 73 of file vortex.F90.
Referenced by getlatestangle(), and uvp().
latestrmax
real(sz) pahm_vortex::latestrmax private
Definition at line 72 of file vortex.F90.
Referenced by getlatestrmax(), and uvp().
npoints
integer, parameter pahm_vortex::npoints = NQUADS + 2 private
Definition at line 44 of file vortex.F90.
nquads
integer, parameter pahm_vortex::nquads = 4 private
Definition at line 43 of file vortex.F90.
Referenced by calcrmaxes(), and calcrmaxesfull().
pc
real(sz) pahm_vortex::pc private
Definition at line 49 of file vortex.F90.
Referenced by calcrmaxesfull(), newvortex(), newvortexfull(), setvortex(), uvp(), and uvpr().
phi
real(sz) pahm_vortex::phi private
Definition at line 57 of file vortex.F90.
Referenced by calcrmaxesfull(), newvortexfull(), uvpr(), and vhwithcorifull().
phis
real(sz), dimension(npoints) pahm_vortex::phis private
Definition at line 58 of file vortex.F90.
Referenced by calcrmaxesfull(), getphifactors(), and newvortexfull().
phis4
real(sz), dimension(npoints, 4) pahm_vortex::phis4 private
Definition at line 59 of file vortex.F90.
Referenced by fitrmaxes4().
pn
real(sz) pahm_vortex::pn private
Definition at line 48 of file vortex.F90.
Referenced by calcrmaxesfull(), newvortex(), newvortexfull(), setvortex(), uvp(), and uvpr().
quad
integer pahm_vortex::quad private
Definition at line 70 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), vhnocori(), vhwithcori(), and vhwithcorifull().
quadflag4
integer, dimension(npoints, 4), public pahm_vortex::quadflag4
Definition at line 65 of file vortex.F90.
Referenced by fitrmaxes4(), parwind::getgahmfields(), and interpr().
quadir4
real(sz), dimension(npoints, 4), public pahm_vortex::quadir4
Definition at line 66 of file vortex.F90.
Referenced by fitrmaxes4(), parwind::getgahmfields(), and interpr().
radius
real(sz), dimension(nquads) pahm_vortex::radius private
Definition at line 68 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), setisotachradii(), vhnocori(), vhwithcori(), and vhwithcorifull().
rmaxes
real(sz), dimension(npoints) pahm_vortex::rmaxes private
Definition at line 45 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), fitrmaxes(), getrmaxes(), rmw(), and setrmaxes().
rmaxes4
real(sz), dimension(npoints, 4), public pahm_vortex::rmaxes4
Definition at line 46 of file vortex.F90.
Referenced by fitrmaxes4(), parwind::getgahmfields(), and spinterp().
usequadrantvr
logical pahm_vortex::usequadrantvr private
Definition at line 74 of file vortex.F90.
Referenced by getusequadrantvr(), and setusequadrantvr().
usevmaxesbl
logical pahm_vortex::usevmaxesbl private
Definition at line 75 of file vortex.F90.
Referenced by setusevmaxesbl().
vmax
real(sz) pahm_vortex::vmax private
Definition at line 52 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), newvortex(), newvortexfull(), uvp(), uvpr(), vhnocori(), vhwithcori(), and vhwithcorifull().
vmbl
real(sz), dimension(npoints) pahm_vortex::vmbl private
Definition at line 63 of file vortex.F90.
Referenced by calcrmaxes(), calcrmaxesfull(), getvmaxesbl(), newvortex(), newvortexfull(), and setvmaxesbl().
vmbl4
real(sz), dimension(npoints, 4), public pahm_vortex::vmbl4
Definition at line 64 of file vortex.F90.
Referenced by fitrmaxes4(), parwind::getgahmfields(), and spinterp().
vr
real(sz) pahm_vortex::vr private
Definition at line 56 of file vortex.F90.
Referenced by setisotachwindspeed(), vhnocori(), vhwithcori(), and vhwithcorifull().
vrquadrant
real(sz), dimension(nquads) pahm_vortex::vrquadrant private
Definition at line 67 of file vortex.F90.
Referenced by setisotachwindspeeds(), vhnocori(), vhwithcori(), and vhwithcorifull().