PaHM: csv_module Module Reference
csv_module Module Reference
Data Types
type csv_file
type csv_string
Functions/Subroutines
subroutine initialize_csv_file (me, quote, delimiter, enclose_strings_in_quotes, enclose_all_in_quotes, logical_true_string, logical_false_string, chunk_size)
Initialize a [[csv_file(type)]].
subroutine destroy_csv_file (me)
Destroy a [[csv_file(type)]].
subroutine read_csv_file (me, filename, header_row, skip_rows, status_ok)
Reads a CSV file.
subroutine open_csv_file (me, filename, n_cols, status_ok, append)
Open a CSV file for writing.
subroutine close_csv_file (me, status_ok)
Close a CSV file after writing.
subroutine add_cell (me, val, int_fmt, real_fmt, trim_str)
Adds a cell to a CSV file.
subroutine add_vector (me, val, int_fmt, real_fmt, trim_str)
Adds a vector to a CSV file.
subroutine add_matrix (me, val, int_fmt, real_fmt, trim_str)
Adds a matrix to a CSV file.
subroutine next_row (me)
Advance to the next row in the CSV file (write any blank cells that are necessary to finish the row).
subroutine get_header_csv_str (me, header, status_ok)
Returns the header as a 'type(csv_string)' array ('read' must have already been called to read the file).
subroutine get_header_str (me, header, status_ok)
Returns the header as a 'character(len=*)' array.
subroutine get_csv_data_as_str (me, csv_data, status_ok)
Returns a 'character(len=*)' array containing the csv data ('read' must have already been called to read the file).
pure elemental subroutine to_real (str, val, status_ok)
Converts a string to a 'real(wp)'.
pure elemental subroutine to_integer (str, val, status_ok)
Converts a string to a 'integer(ip)'.
pure elemental subroutine to_logical (str, val, status_ok)
Converts a string to a 'logical'.
subroutine variable_types (me, itypes, status_ok)
Returns an array indicating the variable type of each columns.
subroutine infer_variable_type (str, itype)
Infers the variable type.
subroutine csv_get_value (me, row, col, val, status_ok)
Get an individual value from the 'csv_data' structure in the CSV class.
subroutine get_column (me, icol, r, status_ok)
Return a column from a CSV file vector.
subroutine get_real_column (me, icol, r, status_ok)
Return a column from a CSV file as a 'real(wp)' vector.
subroutine get_integer_column (me, icol, r, status_ok)
Return a column from a CSV file as a 'integer(ip)' vector.
subroutine get_logical_column (me, icol, r, status_ok)
Convert a column from a 'csv_string' matrix to a 'logical' vector.
subroutine get_character_column (me, icol, r, status_ok)
Convert a column from a 'csv_string' matrix to a 'character(len=*)' vector.
subroutine get_csv_string_column (me, icol, r, status_ok)
Convert a column from a 'csv_string' matrix to a 'type(csv_string)' vector.
subroutine tokenize_csv_line (me, line, cells)
Tokenize a line from a CSV file.
integer function number_of_lines_in_file (iunit)
Returns the number of lines in a text file.
subroutine read_line_from_file (me, iunit, line, status_ok)
Reads the next line from a file.
pure subroutine split (str, token, chunk_size, vals)
Splits a character string using a token.
Variables
integer, parameter, public csv_type_string = 1
integer, parameter, public csv_type_double = 2
integer, parameter, public csv_type_integer = 3
integer, parameter, public csv_type_logical = 4
real(wp), parameter zero = 0.0_wp
Function/Subroutine Documentation
add_cell()
subroutine csv_module::add_cell (class(csv_file), intent(inout) me, class(*), intent(in) val, character(len=*), intent(in), optional int_fmt, character(len=*), intent(in), optional real_fmt, logical, intent(in), optional trim_str) private
Adds a cell to a CSV file.
Parameters
[in,out] me The input/ouput csv_file class
[in] val The value to add
[in] int_fmt If 'val' is an integer, use this format string (optional)
[in] real_fmt If 'val' is a real, use this format string (optional)
[out] trim_str If 'val' is a string, then trim it (optional)
Definition at line 537 of file csv_module.F90.
References csv_parameters::default_int_fmt, csv_parameters::default_real_fmt, pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::unsetmessagesource(), and pahm_sizes::wp.
Referenced by csv_module::csv_file::add().
add_matrix()
subroutine csv_module::add_matrix (class(csv_file), intent(inout) me, class(*), dimension(:,:), intent(in) val, character(len=*), intent(in), optional int_fmt, character(len=*), intent(in), optional real_fmt, logical, intent(in), optional trim_str) private
Adds a matrix to a CSV file.
Each row is added as a new line. Line breaks are added at the end of each line (in this way it differs from the other 'add' routines).
Parameters
[in,out] me The input/ouput csv_file class
[in] val The values to add
[in] int_fmt If 'val' is an integer, use this format string (optional)
[in] real_fmt If 'val' is a real, use this format string (optional)
[out] trim_str If 'val' is a string, then trim it (optional)
Definition at line 714 of file csv_module.F90.
Referenced by csv_module::csv_file::add().
add_vector()
subroutine csv_module::add_vector (class(csv_file), intent(inout) me, class(*), dimension(:), intent(in) val, character(len=*), intent(in), optional int_fmt, character(len=*), intent(in), optional real_fmt, logical, intent(in), optional trim_str) private
Adds a vector to a CSV file.
Each element is added as a cell to the current line.
Parameters
[in,out] me The input/ouput csv_file class
[in] val The values to add
[in] int_fmt If 'val' is an integer, use this format string (optional)
[in] real_fmt If 'val' is a real, use this format string (optional)
[out] trim_str If 'val' is a string, then trim it (optional)
Definition at line 659 of file csv_module.F90.
Referenced by csv_module::csv_file::add().
close_csv_file()
subroutine csv_module::close_csv_file (class(csv_file), intent(inout) me, logical, intent(out) status_ok) private
Close a CSV file after writing.
Parameters
[in,out] me The input/ouput csv_file class
[out] status_ok Status flag
Definition at line 499 of file csv_module.F90.
csv_get_value()
subroutine csv_module::csv_get_value (class(csv_file), intent(inout) me, integer, intent(in) row, integer, intent(in) col, class(*), intent(out) val, logical, intent(out) status_ok) private
Get an individual value from the 'csv_data' structure in the CSV class.
The output 'val' can be an 'integer(ip)', 'real(wp)', 'logical', or 'character(len=*)' variable.
Parameters
[in,out] me The input/ouput csv_file class
[in] row The row number
[in] col The column number
[out] val The returned value
[out] status_ok Status flag
Definition at line 1200 of file csv_module.F90.
References to_integer(), to_logical(), to_real(), and pahm_sizes::wp.
Referenced by csv_module::csv_file::get().
destroy_csv_file()
subroutine csv_module::destroy_csv_file (class(csv_file), intent(out) me) private
Destroy a [[csv_file(type)]].
Parameters
[out] me The ouput csv_file class
Definition at line 229 of file csv_module.F90.
get_character_column()
subroutine csv_module::get_character_column (class(csv_file), intent(inout) me, integer, intent(in) icol, character(len=*), dimension(:), intent(out), allocatable r, logical, intent(out) status_ok) private
Convert a column from a 'csv_string' matrix to a 'character(len=*)' vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column
[out] status_ok Status flag
Definition at line 1480 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
get_column()
subroutine csv_module::get_column (class(csv_file), intent(inout) me, integer, intent(in) icol, class(*), dimension(:), intent(out) r, logical, intent(out) status_ok) private
Return a column from a CSV file vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column. It is assumed to have been allocated to the correct size by the caller ('n_rows').
[out] status_ok Status flag
Note
This routine requires that the 'r' array already be allocated. This is because Fortran doesn't want to allow to you pass a non-polymorphic variable into a routine with a dummy variable with 'class(*),dimension(:),allocatable,intent(out)' attributes.
Definition at line 1260 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::unsetmessagesource(), pahm_sizes::wp, and zero.
get_csv_data_as_str()
subroutine csv_module::get_csv_data_as_str (class(csv_file), intent(inout) me, character(len=*), dimension(:,:), intent(out), allocatable csv_data, logical, intent(out) status_ok) private
Returns a 'character(len=*)' array containing the csv data ('read' must have already been called to read the file).
Parameters
[in,out] me The input/ouput csv_file class
[out] csv_data The data
[out] status_ok Status flag
Definition at line 897 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
get_csv_string_column()
subroutine csv_module::get_csv_string_column (class(csv_file), intent(inout) me, integer, intent(in) icol, type(csv_string), dimension(:), intent(out), allocatable r, logical, intent(out) status_ok) private
Convert a column from a 'csv_string' matrix to a 'type(csv_string)' vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column
[out] status_ok Status flag
Definition at line 1524 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
get_header_csv_str()
subroutine csv_module::get_header_csv_str (class(csv_file), intent(inout) me, type(csv_string), dimension(:), intent(out), allocatable header, logical, intent(out) status_ok) private
Returns the header as a 'type(csv_string)' array ('read' must have already been called to read the file).
Parameters
[in,out] me The input/ouput csv_file class
[out] header The header of the CSV file
[out] status_ok Status flag
Definition at line 799 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get_header().
get_header_str()
subroutine csv_module::get_header_str (class(csv_file), intent(inout) me, character(len=*), dimension(:), intent(out), allocatable header, logical, intent(out) status_ok) private
Returns the header as a 'character(len=*)' array.
('read' must have already been called to read the file).
Parameters
[in,out] me The input/ouput csv_file class
[out] header The header of the CSV file
[out] status_ok Status flag
Definition at line 848 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get_header().
get_integer_column()
subroutine csv_module::get_integer_column (class(csv_file), intent(inout) me, integer, intent(in) icol, integer(ip), dimension(:), intent(out), allocatable r, logical, intent(out) status_ok) private
Return a column from a CSV file as a 'integer(ip)' vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column
[out] status_ok Status flag
Definition at line 1392 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
get_logical_column()
subroutine csv_module::get_logical_column (class(csv_file), intent(inout) me, integer, intent(in) icol, logical, dimension(:), intent(out), allocatable r, logical, intent(out) status_ok) private
Convert a column from a 'csv_string' matrix to a 'logical' vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column
[out] status_ok Status flag
Definition at line 1436 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
get_real_column()
subroutine csv_module::get_real_column (class(csv_file), intent(inout) me, integer, intent(in) icol, real(wp), dimension(:), intent(out), allocatable r, logical, intent(out) status_ok) private
Return a column from a CSV file as a 'real(wp)' vector.
Parameters
[in,out] me The input/ouput csv_file class
[in] icol The column number
[out] r The returned column
[out] status_ok Status flag
Definition at line 1348 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::csv_file::get().
infer_variable_type()
subroutine csv_module::infer_variable_type (character(len=*), intent(in) str, integer, intent(out) itype) private
Infers the variable type.
Infers the variable type, assuming the following precedence:
   integer, double, logical, character
Parameters
[in] str The input string
[out] itype The type of the cell value
   1: a character string cell
   2: a 'real(wp)' cell
   3: an 'integer(ip)' cell
   4: a logical cell
[out] status_ok Status flag
Definition at line 1142 of file csv_module.F90.
References csv_type_double, csv_type_integer, csv_type_logical, csv_type_string, to_integer(), to_logical(), and to_real().
Referenced by variable_types().
initialize_csv_file()
subroutine csv_module::initialize_csv_file (class(csv_file), intent(out) me, character(len=1), intent(in), optional quote, character(len=1), intent(in), optional delimiter, logical, intent(in), optional enclose_strings_in_quotes, logical, intent(in), optional enclose_all_in_quotes, character(len=1), intent(in), optional logical_true_string, character(len=1), intent(in), optional logical_false_string, integer, intent(in), optional chunk_size)
Initialize a [[csv_file(type)]].
Parameters
[out] me The ouput csv_file class
[in] quote Can only be one character (optional, default is '"')
[in] delimiter Can only be one character (optional, default is ',')
[in] enclose_strings_in_quotes Logical flag; if true, all string cells will be
enclosed in quotes (optional, default is 'T')
[in] enclose_all_in_quotes Logical flag; if true, all cells will be
enclosed in quotes (optional, default is 'F')
[in] logical_true_string Logical flag; when writing a logical 'true' value to
a CSV file, this is the string to use (optional, default is 'T')
[in] logical_false_string Logical flag; when writing a logical 'false' value to
a CSV file, this is the string to use (optional, default is 'T')
[in] chunk_size Factor for expanding vectors (default is 100)
Definition at line 166 of file csv_module.F90.
next_row()
subroutine csv_module::next_row (class(csv_file), intent(inout) me) private
Advance to the next row in the CSV file (write any blank cells that are necessary to finish the row).
Parameters
[in,out] me The input/ouput csv_file class
Definition at line 749 of file csv_module.F90.
number_of_lines_in_file()
integer function csv_module::number_of_lines_in_file (integer, intent(in) iunit) private
Returns the number of lines in a text file.
Parameters
[in] iunit The file unit number (assumed to be open)
Returns
n_lines The number of lines in the file
Note
It rewinds the file back to the beginning when finished.
Definition at line 1630 of file csv_module.F90.
Referenced by read_csv_file().
open_csv_file()
subroutine csv_module::open_csv_file (class(csv_file), intent(inout) me, character(len=*), intent(in) filename, integer, intent(in) n_cols, logical, intent(out) status_ok, logical, intent(in), optional append) private
Open a CSV file for writing.
Use 'initialize' to set options for the CSV file.
Parameters
[in,out] me The input/ouput csv_file class
[in] filename The CSV file to open
[in] n_cols The number of columns in the file
[out] status_ok Status flag
[in] append Logical flag, append if file exists (optional)
Definition at line 437 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
read_csv_file()
subroutine csv_module::read_csv_file (class(csv_file), intent(inout) me, character(len=*), intent(in) filename, integer, intent(in), optional header_row, integer, dimension(:), intent(in), optional skip_rows, logical, intent(out) status_ok) private
Reads a CSV file.
Parameters
[in,out] me The input/ouput csv_file class
[in] filename The CSV file to open
[out] status_ok Status flag
[in] header_row The header row (optional)
[in] skip_rows The number of rows to skip (optional)
Definition at line 259 of file csv_module.F90.
References pahm_messages::error, pahm_messages::info, pahm_global::lun_btrk, number_of_lines_in_file(), utilities::openfileforread(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::terminate(), csv_utilities::unique(), and pahm_messages::unsetmessagesource().
read_line_from_file()
subroutine csv_module::read_line_from_file (class(csv_file), intent(in) me, integer, intent(in) iunit, character(len=:), intent(out), allocatable line, logical, intent(out) status_ok) private
Reads the next line from a file.
Parameters
[in,out] me The input/ouput csv_file class
[in] iunit The file unit number (assumed to be open)
[out] line The line in the file
[out] status_ok Status flag
Definition at line 1672 of file csv_module.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
split()
pure subroutine csv_module::split (character(len=*), intent(in) str, character(len=*), intent(in) token, integer, intent(in) chunk_size, type(csv_string), dimension(:), intent(out), allocatable vals) private
Splits a character string using a token.
This routine is inspired by the Python split function.
   ### Example
   ''''Fortran
      character(len=:),allocatable :: s
      type(csv_string),dimension(:),allocatable :: vals
      s = '1,2,3,4,5'
      call split(s,',',vals)
   ''''
Parameters
[in] str The input string
[in] token The tokens to use in spliting the string
[out] chunk_size The chunk size to use for expanding vectors
[out] vals The returned values
Warning
Does not account for tokens contained within quotes string
Definition at line 1745 of file csv_module.F90.
References csv_utilities::expand_vector().
Referenced by tokenize_csv_line().
to_integer()
pure elemental subroutine csv_module::to_integer (character(len=*), intent(in) str, integer(ip), intent(out) val, logical, intent(out) status_ok) private
Converts a string to a 'integer(ip)'.
Parameters
[in] str The input string
[out] val The converted value
[out] status_ok Status flag
Definition at line 986 of file csv_module.F90.
References csv_parameters::default_int_fmt.
Referenced by csv_get_value(), and infer_variable_type().
to_logical()
pure elemental subroutine csv_module::to_logical (character(len=*), intent(in) str, logical, intent(out) val, logical, intent(out) status_ok) private
Converts a string to a 'logical'.
The string match is not case sensitive.
   Evaluates to '.true.'  for strings ['1','t','true','.true.']
   Evaluates to '.false.' for strings ['0','f','false','.false.']
Parameters
[in] str The input string
[out] val The converted value
[out] status_ok Status flag
Definition at line 1028 of file csv_module.F90.
References utilities::tolowercase().
Referenced by csv_get_value(), and infer_variable_type().
to_real()
pure elemental subroutine csv_module::to_real (character(len=*), intent(in) str, real(wp), intent(out) val, logical, intent(out) status_ok) private
Converts a string to a 'real(wp)'.
Parameters
[in] str The input string
[out] val The converted value
[out] status_ok Status flag
Definition at line 948 of file csv_module.F90.
References zero.
Referenced by csv_get_value(), and infer_variable_type().
tokenize_csv_line()
subroutine csv_module::tokenize_csv_line (class(csv_file), intent(inout) me, character(len=*), intent(in) line, type(csv_string), dimension(:), intent(out), allocatable cells) private
Tokenize a line from a CSV file.
The result is an array of 'csv_string' types.
Quotes are removed if the entire cell is contained in quotes.
Parameters
[in,out] me The input/ouput csv_file class
[in] line The line in the CSV file
[out] cells The tokenized cell values
[out] status_ok Status flag
Warning
It does not account for delimiters in quotes (these are treated as a new cell). Need to fix!
Definition at line 1572 of file csv_module.F90.
References split().
variable_types()
subroutine csv_module::variable_types (class(csv_file), intent(inout) me, integer, dimension(:), intent(out), allocatable itypes, logical, intent(out) status_ok) private
Returns an array indicating the variable type of each columns.
Parameters
[in,out] me The input/ouput csv_file class
[out] itypes The type of the cell values
   1: a character string cell
   2: a 'real(wp)' cell
   3: an 'integer(ip)' cell
   4: a logical cell
[out] status_ok Status flag
Note
The first element in the column is used to determine the type.
Definition at line 1088 of file csv_module.F90.
References pahm_messages::error, infer_variable_type(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Variable Documentation
csv_type_double
integer, parameter, public csv_module::csv_type_double = 2
Definition at line 31 of file csv_module.F90.
Referenced by infer_variable_type().
csv_type_integer
integer, parameter, public csv_module::csv_type_integer = 3
Definition at line 32 of file csv_module.F90.
Referenced by infer_variable_type().
csv_type_logical
integer, parameter, public csv_module::csv_type_logical = 4
Definition at line 33 of file csv_module.F90.
Referenced by infer_variable_type().
csv_type_string
integer, parameter, public csv_module::csv_type_string = 1
Definition at line 30 of file csv_module.F90.
Referenced by infer_variable_type().
zero
real(wp), parameter csv_module::zero = 0.0_wp private
Definition at line 35 of file csv_module.F90.
Referenced by get_column(), and to_real().