PaHM: /home/takis/CSDL/parwinds-doc/src/csv_utilities.F90 File Reference
csv_utilities.F90 File Reference
Utility routines.
Modules
module csv_utilities
Functions/Subroutines
pure subroutine, public csv_utilities::expand_vector (vec, n, chunk_size, val, finished)
Add elements to the integer vector in chunks.
integer function, dimension(:), allocatable, public csv_utilities::unique (vec, chunk_size)
Finds the unique elements in a vector of integers.
subroutine, public csv_utilities::sort_ascending (ivec)
Sorts an integer array ivec in increasing order.
recursive subroutine quicksort (ilow, ihigh)
subroutine partition (ilow, ihigh, ipivot)
pure elemental subroutine csv_utilities::swap (i1, i2)
Swap two integer values.
Variables
integer, parameter csv_utilities::max_size_for_insertion_sort = 20
Detailed Description
Utility routines.
Author
Jacob Williams
Copyright
License BSD
Definition in file csv_utilities.F90.
Function/Subroutine Documentation
partition()
subroutine sort_ascending::partition (integer, intent(in) ilow, integer, intent(in) ihigh, integer, intent(out) ipivot) private
Definition at line 214 of file csv_utilities.F90.
References csv_utilities::swap().
Referenced by quicksort().
quicksort()
recursive subroutine sort_ascending::quicksort (integer, intent(in) ilow, integer, intent(in) ihigh) private
Definition at line 177 of file csv_utilities.F90.
References csv_utilities::max_size_for_insertion_sort, partition(), quicksort(), and csv_utilities::swap().
Referenced by quicksort(), and csv_utilities::sort_ascending().