PaHM: sortutils::indexx Interface Reference
sortutils::indexx Interface Reference
Public Member Functions
subroutine indexxint (arr1D, idx1D, status)
Indexes a 1D integer array in ascending order.
subroutine indexxint8 (arr1D, idx1D, status)
Indexes a 1D 32-bit integer array in ascending order.
subroutine indexxstring (arr1D, idx1D, status, caseSens)
Indexes a 1D string array in ascending order.
subroutine indexxsingle (arr1D, idx1D, status)
Indexes a 1D single precision array in ascending order.
subroutine indexxdouble (arr1D, idx1D, status)
Indexes a 1D double precision array in ascending order.
Detailed Description
Definition at line 24 of file sortutils.F90.
Member Function/Subroutine Documentation
indexxdouble()
subroutine sortutils::indexx::indexxdouble (real(hp), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D double precision array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (double precision)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 779 of file sortutils.F90.
References pahm_messages::error, icompxchg(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
indexxint()
subroutine sortutils::indexx::indexxint (integer, dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D integer array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (integer)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 85 of file sortutils.F90.
References pahm_messages::error, icompxchg(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
indexxint8()
subroutine sortutils::indexx::indexxint8 (integer(int8), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D 32-bit integer array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (integer)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 257 of file sortutils.F90.
References pahm_messages::error, icompxchg(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
indexxsingle()
subroutine sortutils::indexx::indexxsingle (real(sp), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D single precision array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (single precision)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 607 of file sortutils.F90.
References pahm_messages::error, icompxchg(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
indexxstring()
subroutine sortutils::indexx::indexxstring (character(len=*), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status, logical, intent(in), optional caseSens)
Indexes a 1D string array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed. Modified version of IndexxInt to account for string comparisons
Parameters
arr1D The array to be indexed (string)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
caseSens Logical flag to request case sensitive sort
Definition at line 430 of file sortutils.F90.
References pahm_messages::error, icompxchg(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), sortutils::stringlexcomp(), and pahm_messages::unsetmessagesource().
The documentation for this interface was generated from the following file:
sortutils.F90