PaHM: timedateutils::timeconv Interface Reference
timedateutils::timeconv Interface Reference
Public Member Functions
subroutine timeconvisec (iYear, iMonth, iDay, iHour, iMin, iSec, timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
subroutine timeconvrsec (iYear, iMonth, iDay, iHour, iMin, rSec, timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
Detailed Description
Definition at line 26 of file timedateutils.F90.
Member Function/Subroutine Documentation
timeconvisec()
subroutine timedateutils::timeconv::timeconvisec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, integer, intent(in) iSec, real(sz), intent(out) timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
The reference date is defined by the global variables: refYear, refMonth, refDay, refHour, refMin and refSec. It uses GregToJulDay and ElapsedSecs functions to calculate the elapsed time from the reference date.
Parameters
iYear The year (integer)
iMonth The month of the year (1-12, integer)
iDay The day of the month (1-31, integer)
iHour The hour of the day (0-23, integer)
iMin The minute of the hour (0-59, integer)
iSec The second of the minute (0-59, integer)
timeSec The elapsed time in seconds (real, output)
Definition at line 125 of file timedateutils.F90.
References timedateutils::elapsedsecs(), pahm_messages::error, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_sizes::rmissv, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::terminate(), and pahm_messages::unsetmessagesource().
timeconvrsec()
subroutine timedateutils::timeconv::timeconvrsec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, real(sz), intent(in) rSec, real(sz), intent(out) timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
The reference date is defined by the global variables: refYear, refMonth, refDay, refHour, refMin and refSec. It uses GregToJulDay and ElapsedSecs functions to calculate the elapsed time from the reference date. Similar to TimeConvISEC but seconds are entered as real numbers to allow for fractions of a second.
Parameters
iYear The year (integer)
iMonth The month of the year (1-12, integer)
iDay The day of the month (1-31, integer)
iHour The hour of the day (0-23, integer)
iMin The minute of the hour (0-59, integer)
rSec The second of the minute (0-59, real)
timeSec The elapsed time in seconds (real, output)
Definition at line 202 of file timedateutils.F90.
References timedateutils::elapsedsecs(), pahm_messages::error, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_sizes::rmissv, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::terminate(), and pahm_messages::unsetmessagesource().
The documentation for this interface was generated from the following file:
timedateutils.F90