PaHM: pahm_messages Module Reference
pahm_messages Module Reference
Data Types
interface allmessage
interface logmessage
interface screenmessage
Functions/Subroutines
subroutine initlogging ()
Initializes logging levels.
subroutine openlogfile ()
Opens the log file for writting.
subroutine closelogfile ()
Closes an opened log file.
subroutine screenmessage_1 (message)
General purpose subroutine to write a message to the screen.
subroutine screenmessage_2 (level, message)
subroutine logmessage_1 (message)
General purpose subroutine to write a message to the log file.
subroutine logmessage_2 (level, message)
subroutine allmessage_1 (message)
General purpose subroutine to write a message to both the screen and the log file.
subroutine allmessage_2 (level, message)
subroutine setmessagesource (source)
Sets the name of the subroutine that is writing log and/or screen messages.
subroutine unsetmessagesource ()
Removes the name of the subroutine that is no longer active.
subroutine programversion ()
Prints on the screen the versioning information of the program.
subroutine programhelp ()
Prints on the screen the help system of the program.
subroutine terminate ()
Terminates the calling program when a fatal error is encountered.
Variables
integer nscreen = 1
integer, parameter debug = -1
integer, parameter echo = 0
integer, parameter info = 1
integer, parameter warning = 2
integer, parameter error = 3
character(len=10), dimension(5) loglevelnames
character(len=50), dimension(100) messagesources
character(len=1024) scratchmessage
character(len=1024) scratchformat
integer sourcenumber
logical logfileopened = .FALSE.
logical loginitcalled = .FALSE.
Function/Subroutine Documentation
allmessage_1()
subroutine pahm_messages::allmessage_1 (character(len=*), intent(in) message)
General purpose subroutine to write a message to both the screen and the log file.
Definition at line 309 of file messages.F90.
allmessage_2()
subroutine pahm_messages::allmessage_2 (integer, intent(in) level, character(len=*), intent(in) message)
Definition at line 321 of file messages.F90.
closelogfile()
subroutine pahm_messages::closelogfile
Closes an opened log file.
Definition at line 148 of file messages.F90.
References logfileopened, and pahm_global::lun_log.
Referenced by pahm_drivermod::pahm_finalize().
initlogging()
subroutine pahm_messages::initlogging
Initializes logging levels.
Initialize the names for the logging levels and the counter for the current subroutine.
Definition at line 81 of file messages.F90.
References loginitcalled, loglevelnames, openlogfile(), and sourcenumber.
Referenced by pahm_drivermod::getprogramcmdlargs(), and pahm_drivermod::pahm_init().
logmessage_1()
subroutine pahm_messages::logmessage_1 (character(len=*), intent(in) message)
General purpose subroutine to write a message to the log file.
This subroutine assumes that the global variable "caller" has been set to the name of the subroutine calling it. Therefore, the SetMessageSource subroutine must be called at the beginning of the subroutine that calls this one, and UnsetMessageSource must be called at the end.
Definition at line 245 of file messages.F90.
logmessage_2()
subroutine pahm_messages::logmessage_2 (integer, intent(in) level, character(len=*), intent(in) message)
Definition at line 269 of file messages.F90.
openlogfile()
subroutine pahm_messages::openlogfile
Opens the log file for writting.
Definition at line 113 of file messages.F90.
References error, pahm_global::logfilename, logfileopened, pahm_global::lun_log, and scratchmessage.
Referenced by initlogging().
programhelp()
subroutine pahm_messages::programhelp
Prints on the screen the help system of the program.
Definition at line 427 of file messages.F90.
References pahm_global::lun_screen, and programversion().
Referenced by pahm_drivermod::getprogramcmdlargs().
programversion()
subroutine pahm_messages::programversion
Prints on the screen the versioning information of the program.
Definition at line 397 of file messages.F90.
References pahm_global::lun_screen.
Referenced by pahm_drivermod::getprogramcmdlargs(), and programhelp().
screenmessage_1()
subroutine pahm_messages::screenmessage_1 (character(len=*), intent(in) message)
General purpose subroutine to write a message to the screen.
General purpose subroutine to write a message to the screen with a certain "logging level", and subject to the user's selection of where to write screen output.
This subroutine assumes that the global variable "caller" has been set to the name of the subroutine calling it. Therefore, the SetMessageSource subroutine must be called at the beginning of the subroutine that calls this one, and UnsetMessageSource must be called at the end.
Definition at line 177 of file messages.F90.
screenmessage_2()
subroutine pahm_messages::screenmessage_2 (integer, intent(in) level, character(len=*), intent(in) message)
Definition at line 201 of file messages.F90.
setmessagesource()
subroutine pahm_messages::setmessagesource (character(len=*), intent(in) source)
Sets the name of the subroutine that is writing log and/or screen messages.
Sets the name of the subroutine that is writing log and/or screen messages. Must use at the start of any subroutine that calls ScreenMessage, LogMessage, or AllMessage.
Definition at line 349 of file messages.F90.
References messagesources, and sourcenumber.
Referenced by pahm_netcdfio::base_netcdfcheckerr(), pahm_vortex::calcintensitychange(), sortutils::indexx::indexxdouble(), sortutils::indexx::indexxint(), sortutils::indexx::indexxint8(), sortutils::indexx::indexxsingle(), sortutils::indexx::indexxstring(), pahm_netcdfio::initadcircnetcdfoutfile(), csv_module::initialize_csv_file(), pahm_netcdfio::netcdfterminate(), pahm_netcdfio::newadcircnetcdfoutfile(), utilities::openfileforread(), pahm_drivermod::pahm_finalize(), pahm_drivermod::pahm_init(), pahm_drivermod::pahm_run(), sortutils::quicksort(), parwind::readbesttrackfile(), utilities::readcontrolfile(), pahm_mesh::readmesh(), pahm_mesh::readmeshasciifort14(), pahm_netcdfio::setrecordcounterandstoretime(), sortutils::sort2(), terminate(), timedateutils::timeconv::timeconvisec(), timedateutils::timeconv::timeconvrsec(), pahm_vortex::uvtrans(), and pahm_netcdfio::writenetcdfrecord().
terminate()
subroutine pahm_messages::terminate
Terminates the calling program when a fatal error is encountered.
Definition at line 452 of file messages.F90.
References error, setmessagesource(), and unsetmessagesource().
Referenced by csv_module::initialize_csv_file(), parwind::readbesttrackfile(), pahm_mesh::readmesh(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
unsetmessagesource()
subroutine pahm_messages::unsetmessagesource
Removes the name of the subroutine that is no longer active.
Removes the name of the subroutine that is no longer writing log and/or screen messages. Must use at the end of any subroutine that calls ScreenMessage, LogMessage, or AllMessage.
Definition at line 376 of file messages.F90.
References sourcenumber.
Referenced by pahm_netcdfio::base_netcdfcheckerr(), pahm_vortex::calcintensitychange(), sortutils::indexx::indexxdouble(), sortutils::indexx::indexxint(), sortutils::indexx::indexxint8(), sortutils::indexx::indexxsingle(), sortutils::indexx::indexxstring(), pahm_netcdfio::initadcircnetcdfoutfile(), csv_module::initialize_csv_file(), pahm_netcdfio::netcdfterminate(), pahm_netcdfio::newadcircnetcdfoutfile(), utilities::openfileforread(), pahm_drivermod::pahm_finalize(), pahm_drivermod::pahm_init(), pahm_drivermod::pahm_run(), sortutils::quicksort(), parwind::readbesttrackfile(), pahm_mesh::readmesh(), pahm_netcdfio::setrecordcounterandstoretime(), sortutils::sort2(), terminate(), timedateutils::timeconv::timeconvisec(), timedateutils::timeconv::timeconvrsec(), pahm_vortex::uvtrans(), and pahm_netcdfio::writenetcdfrecord().
Variable Documentation
debug
integer, parameter pahm_messages::debug = -1
Definition at line 30 of file messages.F90.
echo
integer, parameter pahm_messages::echo = 0
Definition at line 31 of file messages.F90.
error
integer, parameter pahm_messages::error = 3
Definition at line 34 of file messages.F90.
Referenced by pahm_netcdfio::base_netcdfcheckerr(), pahm_vortex::calcintensitychange(), sortutils::indexx::indexxdouble(), sortutils::indexx::indexxint(), sortutils::indexx::indexxint8(), sortutils::indexx::indexxsingle(), sortutils::indexx::indexxstring(), csv_module::initialize_csv_file(), pahm_netcdfio::newadcircnetcdfoutfile(), utilities::openfileforread(), openlogfile(), pahm_drivermod::pahm_run(), sortutils::quicksort(), parwind::readbesttrackfile(), pahm_mesh::readmesh(), sortutils::sort2(), terminate(), timedateutils::timeconv::timeconvisec(), timedateutils::timeconv::timeconvrsec(), and pahm_vortex::uvtrans().
info
integer, parameter pahm_messages::info = 1
Definition at line 32 of file messages.F90.
Referenced by pahm_netcdfio::base_netcdfcheckerr(), csv_module::initialize_csv_file(), pahm_netcdfio::netcdfterminate(), pahm_netcdfio::newadcircnetcdfoutfile(), utilities::openfileforread(), parwind::readbesttrackfile(), pahm_mesh::readmeshasciifort14(), and pahm_netcdfio::setrecordcounterandstoretime().
logfileopened
logical pahm_messages::logfileopened = .FALSE.
Definition at line 43 of file messages.F90.
Referenced by closelogfile(), pahm_messages::logmessage::logmessage_1(), pahm_messages::logmessage::logmessage_2(), and openlogfile().
loginitcalled
logical pahm_messages::loginitcalled = .FALSE.
Definition at line 44 of file messages.F90.
Referenced by initlogging(), pahm_messages::logmessage::logmessage_1(), pahm_messages::logmessage::logmessage_2(), pahm_messages::screenmessage::screenmessage_1(), and pahm_messages::screenmessage::screenmessage_2().
loglevelnames
character(len=10), dimension(5) pahm_messages::loglevelnames
Definition at line 36 of file messages.F90.
Referenced by initlogging(), pahm_messages::logmessage::logmessage_2(), and pahm_messages::screenmessage::screenmessage_2().
messagesources
character(len=50), dimension(100) pahm_messages::messagesources
Definition at line 37 of file messages.F90.
Referenced by pahm_messages::logmessage::logmessage_1(), pahm_messages::logmessage::logmessage_2(), pahm_messages::screenmessage::screenmessage_1(), pahm_messages::screenmessage::screenmessage_2(), and setmessagesource().
nscreen
integer pahm_messages::nscreen = 1
Definition at line 27 of file messages.F90.
Referenced by pahm_messages::screenmessage::screenmessage_1(), and pahm_messages::screenmessage::screenmessage_2().
scratchformat
character(len=1024) pahm_messages::scratchformat
Definition at line 39 of file messages.F90.
Referenced by pahm_netcdfio::setrecordcounterandstoretime().
scratchmessage
character(len=1024) pahm_messages::scratchmessage
Definition at line 38 of file messages.F90.
Referenced by pahm_vortex::calcintensitychange(), sortutils::indexx::indexxdouble(), sortutils::indexx::indexxint(), sortutils::indexx::indexxint8(), sortutils::indexx::indexxsingle(), sortutils::indexx::indexxstring(), csv_module::initialize_csv_file(), pahm_netcdfio::newadcircnetcdfoutfile(), utilities::openfileforread(), openlogfile(), pahm_drivermod::pahm_run(), sortutils::quicksort(), parwind::readbesttrackfile(), pahm_mesh::readmesh(), pahm_netcdfio::setrecordcounterandstoretime(), sortutils::sort2(), timedateutils::timeconv::timeconvisec(), timedateutils::timeconv::timeconvrsec(), and pahm_vortex::uvtrans().
sourcenumber
integer pahm_messages::sourcenumber
Definition at line 40 of file messages.F90.
Referenced by initlogging(), pahm_messages::logmessage::logmessage_1(), pahm_messages::logmessage::logmessage_2(), pahm_messages::screenmessage::screenmessage_1(), pahm_messages::screenmessage::screenmessage_2(), setmessagesource(), and unsetmessagesource().
warning
integer, parameter pahm_messages::warning = 2
Definition at line 33 of file messages.F90.