PaHM: parwind Module Reference
parwind Module Reference
Data Types
type asymetricvortexdata_t
type besttrackdata_t
type hollanddata_t
Functions/Subroutines
subroutine readbesttrackfile ()
Subroutine to read all a-deck/b-deck best track files (ATCF format).
subroutine readcsvbesttrackfile ()
Subroutine to read all a-deck/b-deck best track files (ATCF format).
subroutine processhollanddata (idTrFile, strOut, status)
Subroutine to support the Holland model(s) (GetHollandFields).
subroutine processasymmetricvortexdata (idTrFile, strOut, status)
Subroutine to support the asymetric vortex model(s) (Holland or otherwise).
subroutine gethollandfields (timeIDX)
Calculates wind velocities and MSL pressures at the mesh nodes from the P-W Holland Wind model.
subroutine getgahmfields (timeIDX)
Calculates wind velocities and MSL pressures at the mesh nodes from the GAHM Wind model.
subroutine writebesttrackdata (inpFile, trackStruc, suffix)
Outputs the post-prossed best track data to file.
subroutine writeasymmetricvortexdata (inpFile, trackStruc, suffix)
Outputs the post-prossed best track data to file.
subroutine allocbtrstruct (str, nRec)
Subroutine to allocate memory for a best track structure.
subroutine deallocbtrstruct (str)
Subroutine to deallocate the memory allocated for a best track structure.
subroutine allochollstruct (str, nRec)
Subroutine to allocate memory for a holland structure.
subroutine deallochollstruct (str)
Subroutine to deallocate memory of an allocated holland structure.
subroutine allocasymvortstruct (str, nRec)
Subroutine to allocate memory for an asymmetric vortex structure.
subroutine deallocasymvortstruct (str)
Subroutine to deallocate memory of an allocated asymetric vortex structure.
Variables
logical geostrophicswitch = .TRUE.
integer geofactor = 1
integer method = 4
integer approach = 2
integer, parameter, private stormnamelen = 10
type(besttrackdata_t), dimension(:), allocatable besttrackdata
type(hollanddata_t), dimension(:), allocatable holstru
type(asymetricvortexdata_t), dimension(:), allocatable asyvortstru
Function/Subroutine Documentation
allocasymvortstruct()
subroutine parwind::allocasymvortstruct (type(asymetricvortexdata_t), intent(inout) str, integer, intent(in) nRec)
Subroutine to allocate memory for an asymmetric vortex structure.
Parameters
[in,out] str The asymmetric vortex structure of type AsymetricVortexData_T
[in] nRec The number of records in the structure
Definition at line 3392 of file parwind.F90.
Referenced by processasymmetricvortexdata().
allocbtrstruct()
subroutine parwind::allocbtrstruct (type(besttrackdata_t), intent(inout) str, integer, intent(in) nRec)
Subroutine to allocate memory for a best track structure.
Parameters
[in,out] str The best track structure of type BestTrackData_T
[in] nRec The number of records in the structure
Definition at line 3124 of file parwind.F90.
Referenced by readbesttrackfile(), and readcsvbesttrackfile().
allochollstruct()
subroutine parwind::allochollstruct (type(hollanddata_t), intent(inout) str, integer, intent(in) nRec)
Subroutine to allocate memory for a holland structure.
Parameters
[in,out] str The holland structure of type HollandData_T
[in] nRec The number of records in the structure
Definition at line 3263 of file parwind.F90.
Referenced by processhollanddata().
deallocasymvortstruct()
subroutine parwind::deallocasymvortstruct (type(asymetricvortexdata_t), intent(inout) str)
Subroutine to deallocate memory of an allocated asymetric vortex structure.
Parameters
[in,out] str The asymetric vortex structure of type AsymetricVortexData_T
Definition at line 3485 of file parwind.F90.
Referenced by getgahmfields().
deallocbtrstruct()
subroutine parwind::deallocbtrstruct (type(besttrackdata_t), intent(inout) str)
Subroutine to deallocate the memory allocated for a best track structure.
Parameters
[in,out] str The best track structure of type BestTrackData_T
Definition at line 3193 of file parwind.F90.
deallochollstruct()
subroutine parwind::deallochollstruct (type(hollanddata_t), intent(inout) str)
Subroutine to deallocate memory of an allocated holland structure.
Parameters
[in,out] str The holland structure of type HollandData_T
Definition at line 3327 of file parwind.F90.
Referenced by gethollandfields().
getgahmfields()
subroutine parwind::getgahmfields (integer, intent(in) timeIDX)
Calculates wind velocities and MSL pressures at the mesh nodes from the GAHM Wind model.
This subroutine takes a wind file in best track format and uses the GHAM GAHM Wind model to calculate the wind fields (10-m wind speed and MSLP).
The format statement takes into account whether the track data is hindcast/nowcast (BEST) or forecast (OFCL).
The first line in the file MUST be a hindcast, since the central pressure and the rmw are carried forward from hindcasts into forecasts. So there needs to be at least one hindcast to carry the data forward.
Assumes geographical coordinates.
Parameters
[in] timeIDX The time location to generate the fields for
Definition at line 2356 of file parwind.F90.
References asyvortstru, pahm_global::backgroundatmpress, pahm_global::basee, pahm_global::besttrackfilename, pahm_vortex::bs4, pahm_global::datestimes, timedateutils::datetime2string(), deallocasymvortstruct(), pahm_global::deg2rad, pahm_vortex::fitrmaxes4(), geofactor, utilities::getlocandratio(), timedateutils::gettimeconvsec(), pahm_mesh::ismeshok, timedateutils::juldaytogreg(), pahm_global::kt2ms, pahm_global::m2nm, pahm_global::mb2kpa, pahm_global::mb2pa, pahm_global::mdbegsimtime, pahm_global::mdoutdt, pahm_global::nbtrfiles, pahm_global::nm2m, pahm_global::noutdt, pahm_mesh::np, pahm_global::omega, pahm_global::one2ten, processasymmetricvortexdata(), pahm_vortex::quadflag4, pahm_vortex::quadir4, pahm_global::rad2deg, pahm_global::rearth, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_vortex::rmaxes4, pahm_vortex::setvortex(), pahm_mesh::sfea, pahm_mesh::slam, utilities::sphericalfracpoint(), pahm_vortex::spinterp(), pahm_global::times, utilities::touppercase(), pahm_vortex::uvpr(), pahm_vortex::vmbl4, pahm_global::wpress, pahm_global::wvelx, and pahm_global::wvely.
Referenced by pahm_drivermod::pahm_run().
gethollandfields()
subroutine parwind::gethollandfields (integer, intent(in) timeIDX)
Calculates wind velocities and MSL pressures at the mesh nodes from the P-W Holland Wind model.
Calculate wind velocities and MSL pressures at the mesh nodes from the P-W Holland Wind model.
The format statement takes into account whether the track data is hindcast/nowcast (BEST) or forecast (OFCL).
The first line in the file MUST be a hindcast, since the central pressure and the rmw are carried forward from hindcasts into forecasts. So there needs to be at least one hindcast to carry the data forward.
Assumes geographical coordinates.
Parameters
[in] timeIDX The time location to generate the fields for
Definition at line 1954 of file parwind.F90.
References pahm_global::backgroundatmpress, pahm_global::basee, pahm_global::besttrackfilename, pahm_global::datestimes, timedateutils::datetime2string(), deallochollstruct(), pahm_global::deg2rad, utilities::getlocandratio(), timedateutils::gettimeconvsec(), holstru, pahm_mesh::ismeshok, timedateutils::juldaytogreg(), pahm_global::mb2kpa, pahm_global::mb2pa, pahm_global::mdbegsimtime, pahm_global::mdoutdt, pahm_global::nbtrfiles, pahm_global::noutdt, pahm_mesh::np, pahm_global::omega, pahm_global::one2ten, processhollanddata(), pahm_global::rad2deg, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_global::rhoair, pahm_mesh::sfea, pahm_mesh::slam, utilities::sphericalfracpoint(), pahm_global::times, pahm_global::windreduction, pahm_global::wpress, pahm_global::wvelx, and pahm_global::wvely.
Referenced by pahm_drivermod::pahm_run().
processasymmetricvortexdata()
subroutine parwind::processasymmetricvortexdata (integer, intent(in) idTrFile, type(asymetricvortexdata_t), intent(out) strOut, integer, intent(out) status)
Subroutine to support the asymetric vortex model(s) (Holland or otherwise).
Subroutine to support asymetric vortex models. Gets the next line from the file, skipping lines that are time repeats.
Does conversions to the proper units.
Uses old values of central pressure and rmw if the line is a forecast, since forecasts do not have that data in them.
Assumes longitude is WEST longitude, latitude is NORTH latitude.
Parameters
[in] idTrFile The ID of the input track file (1, 2, ...)
[out] strOut The AsymetricVortexData_T structure that stores all model generated data (output)
[out] status Error status, 0 = no error (output)
Definition at line 1118 of file parwind.F90.
References allocasymvortstruct(), approach, pahm_global::backgroundatmpress, besttrackdata, pahm_global::besttrackfilename, pahm_vortex::calcrmaxes(), pahm_vortex::calcrmaxesfull(), utilities::charunique(), pahm_global::deg2rad, pahm_vortex::fang(), geostrophicswitch, pahm_vortex::getphifactors(), pahm_vortex::getrmaxes(), pahm_vortex::getshapeparameter(), pahm_vortex::getshapeparameters(), pahm_vortex::getvmaxesbl(), pahm_global::kt2ms, method, pahm_global::ms2kt, pahm_global::nbtrfiles, pahm_vortex::newvortexfull(), pahm_global::nm2m, pahm_global::rad2deg, pahm_vortex::setisotachradii(), pahm_vortex::setisotachwindspeeds(), pahm_vortex::setusequadrantvr(), pahm_vortex::setusevmaxesbl(), pahm_vortex::setvmaxesbl(), utilities::touppercase(), pahm_vortex::uvtranspoint(), pahm_global::windreduction, and writeasymmetricvortexdata().
Referenced by getgahmfields().
processhollanddata()
subroutine parwind::processhollanddata (integer, intent(in) idTrFile, type(hollanddata_t), intent(out) strOut, integer, intent(out) status)
Subroutine to support the Holland model(s) (GetHollandFields).
Subroutine to support the Holland model (GetHollandFields). Gets the next line from the file, skipping lines that are time repeats.
Does conversions to the proper units.
Uses old values of central pressure and rmw if the line is a forecast, since forecasts do not have that data in them.
Assumes longitude is WEST longitude, latitude is NORTH latitude.
Parameters
[in] idTrFile The ID of the input track file (1, 2, ...)
[out] strOut The HollandData_T structure that stores all Holland model generated data (output)
[out] status Error status, 0 = no error (output)
Definition at line 894 of file parwind.F90.
References allochollstruct(), besttrackdata, pahm_vortex::calcintensitychange(), utilities::charunique(), pahm_global::kt2ms, pahm_global::nbtrfiles, pahm_global::nm2m, utilities::touppercase(), and pahm_vortex::uvtrans().
Referenced by gethollandfields().
readbesttrackfile()
subroutine parwind::readbesttrackfile
Subroutine to read all a-deck/b-deck best track files (ATCF format).
It uses fortran format statements (old approach) to read the ATCF formatted track files as follows:
a-deck: guidance information
b-deck: best track information
Skips lines that are time repeats.
Converts parameter values to the proper units.
Assumes longitude is WEST longitude, latitude is NORTH latitude.
Definition at line 266 of file parwind.F90.
References allocbtrstruct(), besttrackdata, pahm_global::besttrackfilename, utilities::charunique(), pahm_messages::error, utilities::getlinerecord(), pahm_messages::info, pahm_global::lun_btrk, pahm_global::lun_btrk1, pahm_global::nbtrfiles, utilities::openfileforread(), pahm_messages::scratchmessage, pahm_messages::setmessagesource(), pahm_messages::terminate(), utilities::touppercase(), pahm_messages::unsetmessagesource(), and writebesttrackdata().
Referenced by pahm_drivermod::pahm_init().
readcsvbesttrackfile()
subroutine parwind::readcsvbesttrackfile
Subroutine to read all a-deck/b-deck best track files (ATCF format).
It uses PaHM's CSV functionality (preferred approach) to read the ATCF formatted track files as follows:
a-deck: guidance information
b-deck: best track information
Skips lines that are time repeats. ???PV check
Converts parameter values to the proper units.
Assumes longitude is WEST longitude, latitude is NORTH latitude.
Definition at line 582 of file parwind.F90.
References allocbtrstruct(), besttrackdata, pahm_global::besttrackfilename, utilities::charunique(), utilities::getlinerecord(), utilities::intvalstr(), pahm_global::nbtrfiles, utilities::openfileforread(), utilities::touppercase(), and writebesttrackdata().
Referenced by pahm_drivermod::pahm_init().
writeasymmetricvortexdata()
subroutine parwind::writeasymmetricvortexdata (character(len=*), intent(in) inpFile, type(asymetricvortexdata_t), intent(in) trackStruc, character(len=*), intent(in), optional suffix)
Outputs the post-prossed best track data to file.
Writes the generated asymetric vortex data in addition to the adjusted best track data into the "extended" best track output file.
Parameters
[in] inpFile The name of the input best track file
[in] trackStruc The "extended" best track data structure that corresponds to the inpFile
[in] suffix The suffix (optional) to be appended to the inpFile (default '_asymvort')
Definition at line 3017 of file parwind.F90.
References pahm_global::lun_btrk, and pahm_global::lun_btrk1.
Referenced by processasymmetricvortexdata().
writebesttrackdata()
subroutine parwind::writebesttrackdata (character(len=*), intent(in) inpFile, type(besttrackdata_t), intent(in) trackStruc, character(len=*), intent(in), optional suffix)
Outputs the post-prossed best track data to file.
Writes the adjusted (or not) best track data to the "adjusted" best track output file.
Parameters
[in] inpFile The name of the input best track file
[in] trackStruc The "adjusted" best track data structure that corresponds to the inpFile
[in] suffix The suffix (optional) to be appended to the inpFile (default '_adj')
Definition at line 2912 of file parwind.F90.
References pahm_global::lun_btrk, and pahm_global::lun_btrk1.
Referenced by readbesttrackfile(), and readcsvbesttrackfile().
Variable Documentation
approach
integer parwind::approach = 2
Definition at line 26 of file parwind.F90.
Referenced by processasymmetricvortexdata().
asyvortstru
type(asymetricvortexdata_t), dimension(:), allocatable parwind::asyvortstru
Definition at line 243 of file parwind.F90.
Referenced by getgahmfields().
besttrackdata
type(besttrackdata_t), dimension(:), allocatable parwind::besttrackdata
Definition at line 118 of file parwind.F90.
Referenced by processasymmetricvortexdata(), processhollanddata(), readbesttrackfile(), and readcsvbesttrackfile().
geofactor
integer parwind::geofactor = 1
Definition at line 25 of file parwind.F90.
Referenced by getgahmfields().
geostrophicswitch
logical parwind::geostrophicswitch = .TRUE.
Definition at line 24 of file parwind.F90.
Referenced by processasymmetricvortexdata().
holstru
type(hollanddata_t), dimension(:), allocatable parwind::holstru
Definition at line 158 of file parwind.F90.
Referenced by gethollandfields().
method
integer parwind::method = 4
Definition at line 26 of file parwind.F90.
Referenced by processasymmetricvortexdata().
stormnamelen
integer, parameter, private parwind::stormnamelen = 10 private
Definition at line 28 of file parwind.F90.