PaHM: csv_utilities Module Reference
csv_utilities Module Reference
Functions/Subroutines
pure subroutine, public expand_vector (vec, n, chunk_size, val, finished)
Add elements to the integer vector in chunks.
integer function, dimension(:), allocatable, public unique (vec, chunk_size)
Returns only the unique elements of the vector.
subroutine, public sort_ascending (ivec)
Sorts an integer array ivec in increasing order. Uses a basic recursive quicksort (with insertion sort for partitions with \(\le \) 20 elements).
Function/Subroutine Documentation
expand_vector()
pure subroutine, public csv_utilities::expand_vector (integer, dimension(:), intent(inout), allocatable vec, integer, intent(inout) n, integer, intent(in) chunk_size, integer, intent(in), optional val, logical, intent(in), optional finished)
Add elements to the integer vector in chunks.
Parameters
vec The input integer vector (input/output)
n Counter for last element added to vec; must be initialized to size(vec)
(or 0 if not allocated) before first call (input/output)
chunk_size Allocate vec in blocks of this size (>0)
val The value to add to vec (optional)
finished Set to true to return vec as its correct size (n) (optional)
Definition at line 54 of file csv_utilities.F90.
Referenced by csv_module::initialize_csv_file(), and unique().
sort_ascending()
subroutine, public csv_utilities::sort_ascending (integer, dimension(:), intent(inout) ivec)
Sorts an integer array ivec in increasing order. Uses a basic recursive quicksort (with insertion sort for partitions with \(\le \) 20 elements).
Definition at line 142 of file csv_utilities.F90.
References pahm_sizes::ip.
Referenced by unique().
unique()
integer function, dimension(:), allocatable, public csv_utilities::unique (integer, dimension(size(vec)), intent(in) vec, integer, intent(in) chunk_size)
Returns only the unique elements of the vector.
Definition at line 103 of file csv_utilities.F90.
References expand_vector(), and sort_ascending().
Referenced by csv_module::initialize_csv_file().