PaHM: timedateutils Module Reference
timedateutils Module Reference
Data Types
interface gregtojulday
interface splitdatetimestring
interface timeconv
Functions/Subroutines
subroutine timeconvisec (iYear, iMonth, iDay, iHour, iMin, iSec, timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
subroutine timeconvrsec (iYear, iMonth, iDay, iHour, iMin, rSec, timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
logical function leapyear (iYear)
Checks for a leap year.
integer function yeardays (iYear)
Determines the days of the year.
integer function monthdays (iYear, iMonth)
Determines the days in the month of the year.
integer function dayofyear (iYear, iMonth, iDay)
Determines the day of the year.
real(sz) function gregtojuldayisec (iYear, iMonth, iDay, iHour, iMin, iSec, mJD)
Determines the Julian date from a Gregorian date.
real(sz) function gregtojuldayrsec (iYear, iMonth, iDay, iHour, iMin, rSec, mJD)
Determines the Julian date from a Gregorian date.
real(sz) function gregtojulday2 (iDate, iTime, mJD)
Determines the Julian date from a Gregorian date.
subroutine juldaytogreg (julDay, iYear, iMonth, iDay, iHour, iMin, iSec, mJD)
Determines the Julian date from a Gregorian date.
subroutine dayofyeartogreg (inYR, inDY, iYear, iMonth, iDay)
Determines the Gregorian date (year, month, day) from a day of the year.
subroutine splitdatetimestring (inDateTime, iYear, iMonth, iDay, iHour, iMin, iSec)
Splits a date string into components.
subroutine splitdatetimestring2 (inDateTime, iDate, iTime)
Splits a date string into two components.
character(len=len(indatetime)) function preprocessdatetimestring (inDateTime)
Pre-processes an arbitrary date string.
integer function joindate (iYear, iMonth, iDay)
Pre-processes an arbitrary date string.
subroutine splitdate (inDate, iYear, iMonth, iDay)
Pre-processes an arbitrary date string.
character(len=64) function datetime2string (year, month, day, hour, min, sec, sep, units, zone, err)
Constructs a NetCDF time string.
real(sz) function gettimeconvsec (units, invert)
Calculates the conversion factor between time units and seconds.
real(sz) function elapsedsecs (inTime1, inTime2, inUnits)
Calculates the elapsed time in seconds.
Variables
integer, parameter firstgregdate = 1582 * 10000 + 10 * 100 + 05
integer, parameter firstgregtime = 0 * 10000 + 0 * 100 + 0
real(hp), parameter offfirstgregday = 2299150.5_HP
integer, parameter modjuldate = 1858 * 10000 + 11 * 100 + 17
integer, parameter modjultime = 0 * 10000 + 0 * 100 + 0
real(hp), parameter offmodjulday = 2400000.5_HP
integer, parameter unixdate = 1970 * 10000 + 1 * 100 + 1
integer, parameter unixtime = 0 * 10000 + 0 * 100 + 0
real(hp), parameter offunixjulday = 2440587.5_HP
integer, parameter modeldate = 1990 * 10000 + 1 * 100 + 1
integer, parameter modeltime = 0 * 10000 + 0 * 100 + 0
real(hp), parameter offmodeljulday = 2447892.5_HP
integer, parameter usemodjulday = 0
integer, parameter mdjdate = UNIXDATE
integer, parameter mdjtime = UNIXTIME
real(hp), parameter mdjoffset = OFFUNIXJULDAY
Function/Subroutine Documentation
datetime2string()
character(len=64) function timedateutils::datetime2string (integer, intent(in) year, integer, intent(in) month, integer, intent(in) day, integer, intent(in), optional hour, integer, intent(in), optional min, integer, intent(in), optional sec, integer, intent(in), optional sep, character(len=*), intent(in), optional units, character(len=*), intent(in), optional zone, integer, intent(out), optional err)
Constructs a NetCDF time string.
This function joins the values of the year, month, day, hour, min, sec to construct the date string used in NetCDF files.
Parameters
year The year (YYYY)
month The month of the year (MM)
day The day of the month (DD)
hour The hour of the day (hh) (optional - 0 is substituded if not supplied)
min The minute of the hour (mm) (optional - 0 is substituded if not supplied)
sec The second of the minute (ss) (optional - 0 is substituded if not supplied)
sep The seperation character between the date part and the time part
units The units part to be prepented to the datetime string in the form '<units> since'
zone The timezone to use (default none/UTC, optional)
err The error status, no error: status = 0 (output)
Returns
myValOut: The datetime string ([<units> since ]YYYY-MM-DD hh:mm:ss)
Definition at line 1336 of file timedateutils.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::readcontrolfile().
dayofyear()
integer function timedateutils::dayofyear (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay)
Determines the day of the year.
This function calculates "the day of year" number given the year, month, day, for a Gregorian year (>= 1582). In case of an error, the value IMISSV (-999999) is returned.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
iMonth The month of the year (MM, integer, 1 <= MM <= 12)
iDay The day of the month (DD, integer, 1 <= DD <= 31)
Returns
myVal: The day of the year number (also erroneously known as Julian day). This the number of days since the first day of the year (01/01).
Definition at line 460 of file timedateutils.F90.
References pahm_sizes::imissv, and pahm_sizes::rmissv.
dayofyeartogreg()
subroutine timedateutils::dayofyeartogreg (integer, intent(in) inYR, integer, intent(in) inDY, integer, intent(out) iYear, integer, intent(out) iMonth, integer, intent(out) iDay)
Determines the Gregorian date (year, month, day) from a day of the year.
This subroutine computes the calendar year, month and day from given "year" and "day of the year". In case of error, year is set equal to IMISSV (-999999). Gregorian date (after 10/05/1582), or the value RMISSV if an error occurred.
Parameters
inYR The year (YYYY, integer, 1582 <= YYYY)
inDY The day of the year (DDD, integer, 1 <= DDD <= 366)
iYear The year (YYYY, integer, 1582 <= YYYY, output)
iMonth The month of the year (MM, integer, 1 <= MM <=12, output)
iDay The day of the month (DD, integer, 1 <= DD <=31, output)
Definition at line 1011 of file timedateutils.F90.
References juldaytogreg().
elapsedsecs()
real(sz) function timedateutils::elapsedsecs (real(sz), intent(in) inTime1, real(sz), intent(in) inTime2, character(len=*), intent(in), optional inUnits)
Calculates the elapsed time in seconds.
This function computes the elapsed time in sec, between times1 and time2, given the units of the times.
Parameters
inTime1 The start time (real)
inTime2 The end time (real)
inUnits The units (string, optional) of the time variables. Available options:
For converting days to seconds : inUnits = ['DAYS', 'DAY', 'DA', 'D']
For converting hours to seconds: inUnits = ['HOURS', 'HOUR', 'HOU', 'HO', 'H']
For converting seconds to seconds: inUnits = ['SEC', 'SE', 'SC', 'S']
Default: inUnits = ['SEC', 'SE', 'SC', 'S']
Returns
myVal: The elapsed time in seconds (real). If this value is very close, within a tolerance, to the nearest whole number, it is set equal to that number.
Definition at line 1517 of file timedateutils.F90.
References gettimeconvsec().
Referenced by timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
gettimeconvsec()
real(sz) function timedateutils::gettimeconvsec (character(len=*), intent(in) units, integer, intent(in), optional invert)
Calculates the conversion factor between time units and seconds.
This function returns the converion factor between timeUnit and seconds. If invert > 0 then the function returns the inverse conversion factor, seconds to timeUnit.
Parameters
units The time unit used in the calculations (string: S, M, H, D, W)
invert To perform the inverted conversion, froms seconds to timeUnit (optional)
where: S=seconds, M=minutes, H=hours, D=days, W=weeks
Returns
myValOut: The conversion factor
Definition at line 1431 of file timedateutils.F90.
Referenced by utilities::checkcontrolfileinputs(), elapsedsecs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::readcontrolfile().
gregtojulday2()
real(sz) function timedateutils::gregtojulday2 (integer, intent(in) iDate, integer, intent(in) iTime, integer, intent(in), optional mJD)
Determines the Julian date from a Gregorian date.
This function returns the so called Julian day number given a Gregorian date (after 10/05/1582), or the value RMISSV (-999999.0) if an error occurred.
The Julian day number of a date is the number of days that has passed since January 1, 4712 BC at 12h00 (Gregorian). It is usefull to compute differences between dates.
Similar to GregToJulDayISEC but the seconds number is real to allow for second fractions.
Parameters
iDate The date as YYYYMMDD (integer)
 YYYY      The year (YYYY, integer, 1582 <= YYYY)
   MM      The month of the year (MM, integer, 1 <= MM <=12)
   DD      The day of the month (DD, integer, 1 <= DD <=31)
iTime The time as hhmmss (integer)
   hh      The hour of the day (integer, 0 <= hh <= 23)
   mm      The minute of the hour (integer, 0 <= mm <= 59)
   ss      The second of the minute (integer, 0 <= ss <= 60)
mJD Flag to use a modified julian day number or not
   To use a modified julian day number use: mJD >= 1
   otherwise use:                      mJD  < 1
   default: mJD = 0
   The modified julian day number (MJD) was defined in
   the mid 1950's in the interests of astronomy and space science
   as MJD = JD - 2400000.5. The half day shift makes the day start
   at midnight, which is the current time standard.
   Subtracting the large number shifts the zero day to a more
   recent time (November 17, 1858, midnight) allowing smaller numbers
   to represent time.
Returns
myVal: The julian day number (days) since January 1, 4713 BC at 12h00
Note
The code was adopted from the D-Flow FM source (time_module.f90/JULIAN)
Definition at line 776 of file timedateutils.F90.
gregtojuldayisec()
real(sz) function timedateutils::gregtojuldayisec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, integer, intent(in) iSec, integer, intent(in), optional mJD)
Determines the Julian date from a Gregorian date.
This function returns the so called Julian day number given a Gregorian date (after 10/05/1582), or the value RMISSV (-999999.0) if an error occurred.
The Julian day number of a date is the number of days that has passed since January 1, 4712 BC at 12h00 (Gregorian). It is usefull to compute differences between dates.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
iMonth The month of the year (MM, integer, 1 <= MM <=12)
iDay The day of the month (DD, integer, 1 <= DD <=31)
iHour The hour of the day (hh, integer, 0 <= hh <= 23)
iMin The minute of the hour (mm, integer, 0 <= mm <= 59)
iSec iSec The second of the minute (ss, integer, 0 <= ss <= 59)
mJD Flag to use a modified julian day number or not
   To use a modified julian day number use: mJD >= 1
   otherwise use:                      mJD  < 1
   default: mJD = 0
   The modified julian day number (MJD) was defined in
   the mid 1950's in the interests of astronomy and space science
   as MJD = JD - 2400000.5. The half day shift makes the day start
   at midnight, which is the current time standard.
   Subtracting the large number shifts the zero day to a more
   recent time (November 17, 1858, midnight) allowing smaller numbers
   to represent time.
Returns
myVal: The julian day number (days) since January 1, 4713 BC at 12h00
Note
The code was adopted from the D-Flow FM source (time_module.f90/JULIAN)
Definition at line 536 of file timedateutils.F90.
gregtojuldayrsec()
real(sz) function timedateutils::gregtojuldayrsec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, real(sz), intent(in) rSec, integer, intent(in), optional mJD)
Determines the Julian date from a Gregorian date.
This function returns the so called Julian day number given a Gregorian date (after 10/05/1582), or the value RMISSV (-999999.0) if an error occurred.
The Julian day number of a date is the number of days that has passed since January 1, 4712 BC at 12h00 (Gregorian). It is usefull to compute differences between dates.
Similar to GregToJulDayISEC but the seconds number is real to allow for second fractions.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
iMonth The month of the year (MM, integer, 1 <= MM <=12)
iDay The day of the month (DD, integer, 1 <= DD <=31)
iHour The hour of the day (hh, integer, 0 <= hh <= 23)
iMin The minute of the hour (mm, integer, 0 <= mm <= 59)
rSec The second of the minute (ss, real, 0 <= ss <= 59)
mJD Flag to use a modified julian day number or not
   To use a modified julian day number use: mJD >= 1
   otherwise use:                      mJD  < 1
   default: mJD = 0
   The modified julian day number (MJD) was defined in
   the mid 1950's in the interests of astronomy and space science
   as MJD = JD - 2400000.5. The half day shift makes the day start
   at midnight, which is the current time standard.
   Subtracting the large number shifts the zero day to a more
   recent time (November 17, 1858, midnight) allowing smaller numbers
   to represent time.
Returns
myVal: The julian day number (days) since January 1, 4713 BC at 12h00
Note
The code was adopted from the D-Flow FM source (time_module.f90/JULIAN)
Definition at line 655 of file timedateutils.F90.
joindate()
integer function timedateutils::joindate (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay)
Pre-processes an arbitrary date string.
This function joins the three integers iYear, iMonth and iDay to calculate the integer inDate (YYYYMMDD). There is no check on the validity of iYear, iMonth, iDay, therefore the user is responsible to supply valid input values.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
iMonth The month of the year (MM, integer, 1 <= MM <=12)
iDay The day of the month (DD, integer, 1 <= DD <=31)
Returns
myValOut: The integer date (YYYYMMDD)
Definition at line 1241 of file timedateutils.F90.
Referenced by utilities::checkcontrolfileinputs(), timedateutils::gregtojulday::gregtojuldayisec(), timedateutils::gregtojulday::gregtojuldayrsec(), utilities::readcontrolfile(), and timedateutils::splitdatetimestring::splitdatetimestring2().
juldaytogreg()
subroutine timedateutils::juldaytogreg (real(sz), intent(in) julDay, integer, intent(out) iYear, integer, intent(out) iMonth, integer, intent(out) iDay, integer, intent(out) iHour, integer, intent(out) iMin, integer, intent(out) iSec, integer, intent(in), optional mJD)
Determines the Julian date from a Gregorian date.
This subroutine computes the calendar year, month, day, hour, minute and second corresponding to a given Julian date. The inverse of this procedure is the function GregToJulDay. In case of error, year is set equal to IMISSV (-999999). Considers Gregorian dates (after 10/05/1582) only.
The Julian day number of a date is the number of days that has passed since January 1, 4712 BC at 12h00 (Gregorian). It is usefull to compute differences between dates.
Parameters
julDay The Julian day number (double).
mJD Flag to use a modified julian day number or not
   To use a modified julian day number use: mJD >= 1
   otherwise use:                      mJD  < 1
   default: mJD = 0
   The modified julian day number (MJD) was defined in
   the mid 1950's in the interests of astronomy and space science
   as MJD = JD - 2400000.5. The half day shift makes the day start
   at midnight, which is the current time standard.
   Subtracting the large number shifts the zero day to a more
   recent time (November 17, 1858, midnight) allowing smaller numbers
   to represent time.
iYear The year (YYYY, integer, 1582 <= YYYY, output)
iMonth The month of the year (MM, integer, 1 <= MM <=12, output)
iDay The day of the month (DD, integer, 1 <= DD <=31, output)
iHour The hour of the day (hh, integer, 0 <= hh <= 23, output)
iMin The minute of the hour (mm, integer, 0 <= mm <= 59, output)
iSec The second of the minute (ss, integer, 0 <= ss <= 59, output)
Note
The code was adopted from the D-Flow FM source (time_module.f90/JULIAN)
Definition at line 899 of file timedateutils.F90.
References mdjoffset, offfirstgregday, and usemodjulday.
Referenced by dayofyeartogreg(), parwind::gethollandfields(), and utilities::readcontrolfile().
leapyear()
logical function timedateutils::leapyear (integer, intent(in) iYear)
Checks for a leap year.
This function tries to determine if a Gregorian year (>= 1582) is a leap year or not.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
Returns
myVal: .TRUE. if it is a leap year or .FALSE. otherwise
Definition at line 315 of file timedateutils.F90.
Referenced by timedateutils::gregtojulday::gregtojulday2(), timedateutils::gregtojulday::gregtojuldayisec(), timedateutils::gregtojulday::gregtojuldayrsec(), monthdays(), and yeardays().
monthdays()
integer function timedateutils::monthdays (integer, intent(in) iYear, integer, intent(in) iMonth)
Determines the days in the month of the year.
This function calculates the number of calendar days in a month of a Gregorian year (>= 1582). In case of an error, the value IMISSV (-999999) is returned.
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
iMonth The month of the year (MM, integer, 1 <= MM <= 12)
Returns
myVal: The days of the month
Definition at line 403 of file timedateutils.F90.
References pahm_sizes::imissv, and leapyear().
Referenced by timedateutils::splitdatetimestring::splitdatetimestring().
preprocessdatetimestring()
character(len=len(indatetime)) function timedateutils::preprocessdatetimestring (character(len=*), intent(in) inDateTime)
Pre-processes an arbitrary date string.
This function returns a date/time string in the format YYYYMMDDhhmmss by removing all non-numeric characters from the string.
Parameters
inDateTime The input date string
Returns
myValOut: The string datetime as an integer in the form: YYYYMMDDhhmmss
Definition at line 1186 of file timedateutils.F90.
Referenced by timedateutils::splitdatetimestring::splitdatetimestring().
splitdate()
subroutine timedateutils::splitdate (integer, intent(in) inDate, integer, intent(out) iYear, integer, intent(out) iMonth, integer, intent(out) iDay)
Pre-processes an arbitrary date string.
This subroutine splits the integer inDate (YYYYMMDD) in three integers that is, "iYear (YYYY)", "iMonth (MM)" and "iDay (DD)". There is no check on the validity of inDate, the user is responsible to supply a valid input date.
Parameters
inDate The integer date (YYYYMMDD)
iYear The year (YYYY, integer, 1582 <= YYYY, output)
iMonth The month of the year (MM, integer, 1 <= MM <=12, output)
iDay The day of the month (DD, integer, 1 <= DD <=31, output)
Note
The code was adopted from the D-Flow FM source (time_module.f90/splitDate)
Definition at line 1281 of file timedateutils.F90.
Referenced by timedateutils::gregtojulday::gregtojulday2().
splitdatetimestring()
subroutine timedateutils::splitdatetimestring (character(len=*), intent(in) inDateTime, integer, intent(out) iYear, integer, intent(out) iMonth, integer, intent(out) iDay, integer, intent(out) iHour, integer, intent(out) iMin, integer, intent(out) iSec)
Splits a date string into components.
This subroutine splits the string inDate (YYYYMMDDhhmmss) in six integers that is, "iYear (YYYY)", "iMonth (MM)", "iDay (DD)", "iHour (hh)", "iMin (mm)" and "iSec (ss)".
Parameters
inDateTime The input date string: YYYYMMDDhhmmss
iYear The year (YYYY, integer, 1582 <= YYYY, output)
iMonth The month of the year (MM, integer, 1 <= MM <=12, output)
iDay The day of the month (DD, integer, 1 <= DD <=31, output)
iHour The hour of the day (hh, integer, 0 <= hh <= 23, output)
iMin The minute of the hour (mm, integer, 0 <= mm <= 59, output)
iSec The second of the minute (ss, integer, 0 <= ss <= 59, output)
Definition at line 1073 of file timedateutils.F90.
splitdatetimestring2()
subroutine timedateutils::splitdatetimestring2 (character(len=*), intent(in) inDateTime, integer, intent(out) iDate, integer, intent(out) iTime)
Splits a date string into two components.
This subroutine splits the string inDate (YYYYMMDDhhmmss) in two integers that is, "iDate (YYYYMMDD)" and "iTime (hhmmss)".
Parameters
inDateTime The input date string: YYYYMMDDhhmmss
iDate The integer date (YYYYMMDD, output)
iTime The integer time (hhmmss, output)
Definition at line 1141 of file timedateutils.F90.
timeconvisec()
subroutine timedateutils::timeconvisec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, integer, intent(in) iSec, real(sz), intent(out) timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
The reference date is defined by the global variables: refYear, refMonth, refDay, refHour, refMin and refSec. It uses GregToJulDay and ElapsedSecs functions to calculate the elapsed time from the reference date.
Parameters
iYear The year (integer)
iMonth The month of the year (1-12, integer)
iDay The day of the month (1-31, integer)
iHour The hour of the day (0-23, integer)
iMin The minute of the hour (0-59, integer)
iSec The second of the minute (0-59, integer)
timeSec The elapsed time in seconds (real, output)
Definition at line 125 of file timedateutils.F90.
timeconvrsec()
subroutine timedateutils::timeconvrsec (integer, intent(in) iYear, integer, intent(in) iMonth, integer, intent(in) iDay, integer, intent(in) iHour, integer, intent(in) iMin, real(sz), intent(in) rSec, real(sz), intent(out) timeSec)
Convert time from year, month, day, hour, min, sec into seconds since the reference date of the simulation.
The reference date is defined by the global variables: refYear, refMonth, refDay, refHour, refMin and refSec. It uses GregToJulDay and ElapsedSecs functions to calculate the elapsed time from the reference date. Similar to TimeConvISEC but seconds are entered as real numbers to allow for fractions of a second.
Parameters
iYear The year (integer)
iMonth The month of the year (1-12, integer)
iDay The day of the month (1-31, integer)
iHour The hour of the day (0-23, integer)
iMin The minute of the hour (0-59, integer)
rSec The second of the minute (0-59, real)
timeSec The elapsed time in seconds (real, output)
Definition at line 202 of file timedateutils.F90.
yeardays()
integer function timedateutils::yeardays (integer, intent(in) iYear)
Determines the days of the year.
This function calculates the number of calendar days of a Gregorian year (>= 1582).
Parameters
iYear The year (YYYY, integer, 1582 <= YYYY)
Returns
myVal: The days of the year (365 or 366)
Definition at line 366 of file timedateutils.F90.
References leapyear().
Variable Documentation
firstgregdate
integer, parameter timedateutils::firstgregdate = 1582 * 10000 + 10 * 100 + 05
Definition at line 44 of file timedateutils.F90.
Referenced by utilities::checkcontrolfileinputs(), timedateutils::gregtojulday::gregtojulday2(), timedateutils::gregtojulday::gregtojuldayisec(), and timedateutils::gregtojulday::gregtojuldayrsec().
firstgregtime
integer, parameter timedateutils::firstgregtime = 0 * 10000 + 0 * 100 + 0
Definition at line 45 of file timedateutils.F90.
Referenced by utilities::checkcontrolfileinputs().
mdjdate
integer, parameter timedateutils::mdjdate = UNIXDATE
Definition at line 80 of file timedateutils.F90.
mdjoffset
real(hp), parameter timedateutils::mdjoffset = OFFUNIXJULDAY
Definition at line 82 of file timedateutils.F90.
Referenced by timedateutils::gregtojulday::gregtojulday2(), timedateutils::gregtojulday::gregtojuldayisec(), timedateutils::gregtojulday::gregtojuldayrsec(), and juldaytogreg().
mdjtime
integer, parameter timedateutils::mdjtime = UNIXTIME
Definition at line 81 of file timedateutils.F90.
modeldate
integer, parameter timedateutils::modeldate = 1990 * 10000 + 1 * 100 + 1
Definition at line 65 of file timedateutils.F90.
modeltime
integer, parameter timedateutils::modeltime = 0 * 10000 + 0 * 100 + 0
Definition at line 66 of file timedateutils.F90.
modjuldate
integer, parameter timedateutils::modjuldate = 1858 * 10000 + 11 * 100 + 17
Definition at line 53 of file timedateutils.F90.
modjultime
integer, parameter timedateutils::modjultime = 0 * 10000 + 0 * 100 + 0
Definition at line 54 of file timedateutils.F90.
offfirstgregday
real(hp), parameter timedateutils::offfirstgregday = 2299150.5_HP
Definition at line 46 of file timedateutils.F90.
Referenced by juldaytogreg().
offmodeljulday
real(hp), parameter timedateutils::offmodeljulday = 2447892.5_HP
Definition at line 67 of file timedateutils.F90.
offmodjulday
real(hp), parameter timedateutils::offmodjulday = 2400000.5_HP
Definition at line 55 of file timedateutils.F90.
offunixjulday
real(hp), parameter timedateutils::offunixjulday = 2440587.5_HP
Definition at line 61 of file timedateutils.F90.
unixdate
integer, parameter timedateutils::unixdate = 1970 * 10000 + 1 * 100 + 1
Definition at line 59 of file timedateutils.F90.
unixtime
integer, parameter timedateutils::unixtime = 0 * 10000 + 0 * 100 + 0
Definition at line 60 of file timedateutils.F90.
usemodjulday
integer, parameter timedateutils::usemodjulday = 0
Definition at line 72 of file timedateutils.F90.
Referenced by timedateutils::gregtojulday::gregtojulday2(), timedateutils::gregtojulday::gregtojuldayisec(), timedateutils::gregtojulday::gregtojuldayrsec(), and juldaytogreg().