PaHM: sortutils Module Reference
sortutils Module Reference
Data Types
interface arraycopy
interface arrayequal
interface arth
interface indexx
interface swap
Functions/Subroutines
subroutine indexxint (arr1D, idx1D, status)
Indexes a 1D integer array in ascending order.
subroutine indexxint8 (arr1D, idx1D, status)
Indexes a 1D 32-bit integer array in ascending order.
subroutine indexxstring (arr1D, idx1D, status, caseSens)
Indexes a 1D string array in ascending order.
subroutine indexxsingle (arr1D, idx1D, status)
Indexes a 1D single precision array in ascending order.
subroutine indexxdouble (arr1D, idx1D, status)
Indexes a 1D double precision array in ascending order.
subroutine quicksort (arr1D, status)
Sorts the array arr1D into ascending numerical order using Quicksort.
subroutine sort2 (arr1D, slv1D, status)
Sorts two 1D arrays into ascending numerical order using Quicksort.
subroutine arraycopyint (src, dest, nCP, nNCP)
Copies the 1D source integer array "src" into the 1D destination array "dest".
subroutine arraycopysingle (src, dest, nCP, nNCP)
Copies the 1D source single precision array "src" into the 1D destination array "dest".
subroutine arraycopydouble (src, dest, nCP, nNCP)
Copies the 1D source double precision array "src" into the 1D destination array "dest".
logical function arrayequalint (arr1, arr2)
Compares two one-dimensional integer arrays for equality.
logical function arrayequalsingle (arr1, arr2)
Compares two one-dimensional single precision arrays for equality.
logical function arrayequaldouble (arr1, arr2)
Compares two one-dimensional double precision arrays for equality.
integer function stringlexcomp (str1, str2, mSensitive)
Performs a lexical comparison between two strings.
subroutine swapint (a, b, mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
subroutine swapsingle (a, b, mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
subroutine swapdouble (a, b, mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
subroutine swapintvec (a, b, mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
subroutine swapsinglevec (a, b, mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
subroutine swapdoublevec (a, b, mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
pure integer function, dimension(n) arthint (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
pure real(sp) function, dimension(n) arthsingle (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
pure real(hp) function, dimension(n) arthdouble (first, increment, n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
Function/Subroutine Documentation
arraycopydouble()
subroutine sortutils::arraycopydouble (real(hp), dimension(:), intent(in) src, real(hp), dimension(:), intent(out) dest, integer, intent(out) nCP, integer, intent(out) nNCP)
Copies the 1D source double precision array "src" into the 1D destination array "dest".
Parameters
src The one-dimensional array to be copied (double precision)
dest The copied array (output)
nCP The number of elements of "src" array that copied (output)
nNCP The number of elements of "src" array that failed to be copied (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1247 of file sortutils.F90.
arraycopyint()
subroutine sortutils::arraycopyint (integer, dimension(:), intent(in) src, integer, dimension(:), intent(out) dest, integer, intent(out) nCP, integer, intent(out) nNCP)
Copies the 1D source integer array "src" into the 1D destination array "dest".
Parameters
src The one-dimensional array to be copied (integer)
dest The copied array (output)
nCP The number of elements of "src" array that copied (output)
nNCP The number of elements of "src" array that failed to be copied (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1169 of file sortutils.F90.
arraycopysingle()
subroutine sortutils::arraycopysingle (real(sp), dimension(:), intent(in) src, real(sp), dimension(:), intent(out) dest, integer, intent(out) nCP, integer, intent(out) nNCP)
Copies the 1D source single precision array "src" into the 1D destination array "dest".
Parameters
src The one-dimensional array to be copied (single precision)
dest The copied array (output)
nCP The number of elements of "src" array that copied (output)
nNCP The number of elements of "src" array that failed to be copied (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1208 of file sortutils.F90.
arrayequaldouble()
logical function sortutils::arrayequaldouble (real(hp), dimension(:), intent(in) arr1, real(hp), dimension(:), intent(in) arr2)
Compares two one-dimensional double precision arrays for equality.
The equality is determined using a tolerance of: 0.00000001, such that the two arrays are considered to be essentially equal on double precision calculations.
Parameters
arr1 The first array in the comparison (double precision)
arr2 The second array in the comparison (double precision)
Returns
myValOut: The value of the comparison (logical). TRUE if all the elements of arr1 are equal to all elements of arr2, FALSE otherwise.
Definition at line 1384 of file sortutils.F90.
arrayequalint()
logical function sortutils::arrayequalint (integer, dimension(:), intent(in) arr1, integer, dimension(:), intent(in) arr2)
Compares two one-dimensional integer arrays for equality.
Parameters
arr1 The first array in the comparison (integer)
arr2 The second array in the comparison (integer)
Returns
myValOut: The value of the comparison (logical). TRUE if all the elements of arr1 are equal to all elements of arr2, FALSE otherwise.
Definition at line 1284 of file sortutils.F90.
arrayequalsingle()
logical function sortutils::arrayequalsingle (real(sp), dimension(:), intent(in) arr1, real(sp), dimension(:), intent(in) arr2)
Compares two one-dimensional single precision arrays for equality.
The equality is determined using a tolerance of: 0.00000001, such that the two arrays are considered to be essentially equal on single precision calculations.
Parameters
arr1 The first array in the comparison (single precision)
arr2 The second array in the comparison (single precision)
Returns
myValOut: The value of the comparison (logical). TRUE if all the elements of arr1 are equal to all elements of arr2, FALSE otherwise.
Definition at line 1329 of file sortutils.F90.
arthdouble()
pure real(hp) function, dimension(n) sortutils::arthdouble (real(hp), intent(in) first, real(hp), intent(in) increment, integer, intent(in) n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
Parameters
first The value of the first term (double precision)
increment The value of the increment (double precision)
n The total number of terms in the return 1D array (integer)
Returns
arthOut: The 1D array that contains the arithmetic progression (double precision)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1952 of file sortutils.F90.
arthint()
pure integer function, dimension(n) sortutils::arthint (integer, intent(in) first, integer, intent(in) increment, integer, intent(in) n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
Parameters
first The value of the first term (integer)
increment The value of the increment (integer)
n The total number of terms in the return 1D array (integer)
Returns
arthOut: The 1D array that contains the arithmetic progression (integer)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1818 of file sortutils.F90.
arthsingle()
pure real(sp) function, dimension(n) sortutils::arthsingle (real(sp), intent(in) first, real(sp), intent(in) increment, integer, intent(in) n)
Returns an arithmetic progression, given a first term "first", an increment and a number of terms "n" (including "first").
Parameters
first The value of the first term (single precision)
increment The value of the increment (single precision)
n The total number of terms in the return 1D array (integer)
Returns
arthOut: The 1D array that contains the arithmetic progression (single precision)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1885 of file sortutils.F90.
indexxdouble()
subroutine sortutils::indexxdouble (real(hp), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D double precision array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (double precision)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 779 of file sortutils.F90.
indexxint()
subroutine sortutils::indexxint (integer, dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D integer array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (integer)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 85 of file sortutils.F90.
indexxint8()
subroutine sortutils::indexxint8 (integer(int8), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D 32-bit integer array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (integer)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 257 of file sortutils.F90.
indexxsingle()
subroutine sortutils::indexxsingle (real(sp), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status)
Indexes a 1D single precision array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed.
Parameters
arr1D The array to be indexed (single precision)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 607 of file sortutils.F90.
indexxstring()
subroutine sortutils::indexxstring (character(len=*), dimension(:), intent(in) arr1D, integer, dimension(:), intent(out) idx1D, integer, intent(out), optional status, logical, intent(in), optional caseSens)
Indexes a 1D string array in ascending order.
Indexes the 1D array arr1D, i.e., outputs the array index of length N such that arr1D(idx1D(j)) is in ascending order for j = 1, 2, . . . , N. The input quantity arr1D is not changed. Modified version of IndexxInt to account for string comparisons
Parameters
arr1D The array to be indexed (string)
idx1D The array of "indexed" indexes of arr1D (output)
status The error status, no error: status = 0 (output)
caseSens Logical flag to request case sensitive sort
Definition at line 430 of file sortutils.F90.
quicksort()
subroutine sortutils::quicksort (real(sz), dimension(:), intent(inout) arr1D, integer, intent(out), optional status)
Sorts the array arr1D into ascending numerical order using Quicksort.
The array arr1D is replaced on output by its sorted rearrangement. The parameters NN and NSTACK are defined as:
NN is the size of subarrays sorted by straight insertion, and
NSTACK is the required auxiliary storage
Parameters
arr1D The one-dimensional array to be sorted
status The error status, no error: status = 0 (output)
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 951 of file sortutils.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
sort2()
subroutine sortutils::sort2 (real(sz), dimension(:), intent(inout) arr1D, real(sz), dimension(:), intent(inout) slv1D, integer, intent(out), optional status)
Sorts two 1D arrays into ascending numerical order using Quicksort.
Sorts the array arr1D into ascending order using Quicksort, while making the corresponding rearrangement of the same-size array slv1D. The sorting and rearrangement are performed by means of the index array.
Parameters
arr1D The first one-dimensional array to be sorted in ascending order
slv1D The second one-dimensional array to be sorted in ascending order
status The error status, no error: status = 0 (output)
Returns
The two sorted arrays arr1D and slv1D
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1098 of file sortutils.F90.
References pahm_messages::error, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
stringlexcomp()
integer function sortutils::stringlexcomp (character(len=*), intent(in) str1, character(len=*), intent(in) str2, logical, intent(in), optional mSensitive)
Performs a lexical comparison between two strings.
Parameters
str1 The first string in the comparison
str2 The second string in the comparison
mSensitive Logical flag (.TRUE., .FALSE.) to perform case sensitive lexical comparison
Returns
myValOut: The value of the lexical comparison of the two strings (integer)
   myValOut =  0; str1 == str2
   myValOut = -1; str1 < str2
   myValOut =  1; str1 > str2
Definition at line 1443 of file sortutils.F90.
References utilities::touppercase().
Referenced by sortutils::indexx::indexxstring().
swapdouble()
subroutine sortutils::swapdouble (real(hp), intent(inout) a, real(hp), intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
Parameters
a The first value to be swapped (double precision)
b The second value to be swapped (double precision)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped value
   b: The first swapped value
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1613 of file sortutils.F90.
swapdoublevec()
subroutine sortutils::swapdoublevec (real(hp), dimension(:), intent(inout) a, real(hp), dimension(:), intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (double precision). increment and a number of terms "n" (including "first").
Parameters
a The first 1D array to be swapped (double precision)
b The second 1D array to be swapped (double precision)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped 1D array
   b: The first swapped 1D array
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1769 of file sortutils.F90.
swapint()
subroutine sortutils::swapint (integer, intent(inout) a, integer, intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
Parameters
a The first value to be swapped (integer)
b The second value to be swapped (integer)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped value
   b: The first swapped value
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1509 of file sortutils.F90.
swapintvec()
subroutine sortutils::swapintvec (integer, dimension(:), intent(inout) a, integer, dimension(:), intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (integer). increment and a number of terms "n" (including "first").
Parameters
a The first 1D array to be swapped (integer)
b The second 1D array to be swapped (integer)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped 1D array
   b: The first swapped 1D array
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1665 of file sortutils.F90.
swapsingle()
subroutine sortutils::swapsingle (real(sp), intent(inout) a, real(sp), intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
Parameters
a The first value to be swapped (single precision)
b The second value to be swapped (single precision)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped value
   b: The first swapped value
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1561 of file sortutils.F90.
swapsinglevec()
subroutine sortutils::swapsinglevec (real(sp), dimension(:), intent(inout) a, real(sp), dimension(:), intent(inout) b, logical, intent(in), optional mask)
Swaps the contents of a and b (single precision). increment and a number of terms "n" (including "first").
Parameters
a The first 1D array to be swapped (single precision)
b The second 1D array to be swapped (single precision)
mask Logical flag to perform the swap, default mask = 'TRUE. (optional)
Returns
   a: The second swapped 1D array
   b: The first swapped 1D array
Note
Adopted from Numerical Recipes for Fortran 90
Definition at line 1717 of file sortutils.F90.