PaHM: pahm_global Module Reference
pahm_global Module Reference
Functions/Subroutines
real(sz) function airdensity (atmT, atmP, relHum)
This function calculates the density of the moist air.
Variables
integer, parameter lun_screen = 6
integer, parameter lun_ctrl = 10
integer, parameter lun_inp = 14
integer, parameter lun_inp1 = 15
integer, parameter lun_log = 35
integer, parameter lun_btrk = 22
integer, parameter lun_btrk1 = 23
integer, parameter lun_out = 25
integer, parameter lun_out1 = 26
real(sz), parameter defv_gravity = 9.80665_SZ
real(sz), parameter defv_atmpress = 1013.25_SZ
real(sz), parameter defv_rhoair = 1.1478_SZ
real(sz), parameter defv_rhowater = 1000.0000
real(sz), parameter one2ten = 0.8928_SZ
real(sz), parameter ten2one = 1.0_SZ / 0.8928_SZ
real(sz), parameter pi = 3.141592653589793_SZ
real(sz), parameter deg2rad = PI / 180.0_SZ
real(sz), parameter rad2deg = 180.0_SZ / PI
real(sz), parameter basee = 2.718281828459045_SZ
real(sz), parameter rearth = 6378206.4_SZ
real(sz), parameter nm2m = 1852.0_SZ
real(sz), parameter m2nm = 1.0_SZ / NM2M
real(sz), parameter kt2ms = NM2M / 3600.0_SZ
real(sz), parameter ms2kt = 1.0_SZ / KT2MS
real(sz), parameter omega = 2.0_SZ * PI / 86164.2_SZ
real(sz), parameter mb2pa = 100.0_SZ
real(sz), parameter mb2kpa = 0.1_SZ
character(len=fnamelen) logfilename = TRIM(ADJUSTL(PROG_NAME_LOW)) // '_model.log'
character(fnamelen) controlfilename = TRIM(ADJUSTL(PROG_NAME_LOW)) // '_control.in'
logical meshfilenamespecified = .FALSE.
character(len=fnamelen) meshfilename = BLANK
character(len=64) meshfiletype = BLANK
character(len=64) meshfileform = BLANK
logical besttrackfilenamespecified = .FALSE.
integer nbtrfiles = IMISSV
character(len=fnamelen), dimension(:), allocatable besttrackfilename
character(len=512) title = BLANK
real(sz) gravity = DEFV_GRAVITY
real(sz) rhowater = DEFV_RHOWATER
real(sz) rhoair = DEFV_RHOAIR
real(sz) backgroundatmpress = DEFV_ATMPRESS
real(sz), parameter defv_bladjustfac = 0.9_SZ
real(sz) windreduction = DEFV_BLADJUSTFAC
real(sz) bladjustfac = DEFV_BLADJUSTFAC
character(len=64) refdatetime = BLANK
integer refdate = IMISSV
integer reftime = IMISSV
integer refyear = IMISSV
integer refmonth = 0
integer refday = 0
integer refhour = 0
integer refmin = 0
integer refsec = 0
logical refdatespecified = .FALSE.
character(len=64) begdatetime = BLANK
integer begdate = IMISSV
integer begtime = IMISSV
integer begyear = IMISSV
integer begmonth = 0
integer begday = 0
integer beghour = 0
integer begmin = 0
integer begsec = 0
logical begdatespecified = .FALSE.
character(len=64) enddatetime = BLANK
integer enddate = IMISSV
integer endtime = IMISSV
integer endyear = IMISSV
integer endmonth = 0
integer endday = 0
integer endhour = 0
integer endmin = 0
integer endsec = 0
logical enddatespecified = .FALSE.
real(sz) begsimtime = RMISSV
real(sz) endsimtime = RMISSV
logical begsimspecified = .FALSE.
logical endsimspecified = .FALSE.
character(len=1) unittime = 'S'
real(sz) outdt = RMISSV
integer noutdt = IMISSV
real(sz) mdoutdt = RMISSV
real(sz) mdbegsimtime = RMISSV
real(sz) mdendsimtime = RMISSV
logical outfilenamespecified = .FALSE.
character(len=fnamelen) outfilename = BLANK
integer ncshuffle = 0
integer ncdeflate = 0
integer ncdlevel = 0
character(len=20), parameter def_ncnam_pres = 'P'
character(len=20), parameter def_ncnam_wndx = 'uwnd'
character(len=20), parameter def_ncnam_wndy = 'vwnd'
character(len=20) ncvarnam_pres = DEF_NCNAM_PRES
character(len=20) ncvarnam_wndx = DEF_NCNAM_WNDX
character(len=20) ncvarnam_wndy = DEF_NCNAM_WNDY
integer modeltype = IMISSV
logical writeparams = .FALSE.
real(sz), dimension(:), allocatable wvelx
real(sz), dimension(:), allocatable wvely
real(sz), dimension(:), allocatable wpress
real(sz), dimension(:), allocatable times
Function/Subroutine Documentation
airdensity()
real(sz) function pahm_global::airdensity (real(sz), intent(in) atmT, real(sz), intent(in) atmP, real(sz), intent(in) relHum)
This function calculates the density of the moist air.
See also
https://en.wikipedia.org/wiki/Density_of_air
Parameters
atmT Air temperature (\(^0 C \))
atmP Atmospheric pressure (\(mbar \))
relHum Relative humidity (\(0 - 100 \))
Returns
myValOut: The density of moist air (\(kg / m^3 \))
Definition at line 250 of file global.F90.
Variable Documentation
backgroundatmpress
real(sz) pahm_global::backgroundatmpress = DEFV_ATMPRESS
Definition at line 117 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
basee
real(sz), parameter pahm_global::basee = 2.718281828459045_SZ
Definition at line 78 of file global.F90.
Referenced by parwind::gethollandfields().
begdate
integer pahm_global::begdate = IMISSV
Definition at line 142 of file global.F90.
begdatespecified
logical pahm_global::begdatespecified = .FALSE.
Definition at line 150 of file global.F90.
Referenced by utilities::printmodelparams().
begdatetime
character(len=64) pahm_global::begdatetime = BLANK
Definition at line 141 of file global.F90.
Referenced by utilities::printmodelparams().
begday
integer pahm_global::begday = 0
Definition at line 146 of file global.F90.
Referenced by utilities::printmodelparams().
beghour
integer pahm_global::beghour = 0
Definition at line 147 of file global.F90.
Referenced by utilities::printmodelparams().
begmin
integer pahm_global::begmin = 0
Definition at line 148 of file global.F90.
Referenced by utilities::printmodelparams().
begmonth
integer pahm_global::begmonth = 0
Definition at line 145 of file global.F90.
Referenced by utilities::printmodelparams().
begsec
integer pahm_global::begsec = 0
Definition at line 149 of file global.F90.
Referenced by utilities::printmodelparams().
begsimspecified
logical pahm_global::begsimspecified = .FALSE.
Definition at line 167 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
begsimtime
real(sz) pahm_global::begsimtime = RMISSV
Definition at line 165 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
begtime
integer pahm_global::begtime = IMISSV
Definition at line 143 of file global.F90.
begyear
integer pahm_global::begyear = IMISSV
Definition at line 144 of file global.F90.
Referenced by utilities::printmodelparams().
besttrackfilename
character(len=fnamelen), dimension(:), allocatable pahm_global::besttrackfilename
Definition at line 108 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), utilities::printmodelparams(), parwind::readbesttrackfile(), and parwind::readcsvbesttrackfile().
besttrackfilenamespecified
logical pahm_global::besttrackfilenamespecified = .FALSE.
Definition at line 106 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
bladjustfac
real(sz) pahm_global::bladjustfac = DEFV_BLADJUSTFAC
Definition at line 122 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
controlfilename
character(fnamelen) pahm_global::controlfilename = TRIM(ADJUSTL(PROG_NAME_LOW)) // '_control.in'
Definition at line 99 of file global.F90.
Referenced by pahm_drivermod::getprogramcmdlargs().
def_ncnam_pres
character(len=20), parameter pahm_global::def_ncnam_pres = 'P'
Definition at line 190 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
def_ncnam_wndx
character(len=20), parameter pahm_global::def_ncnam_wndx = 'uwnd'
Definition at line 190 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
def_ncnam_wndy
character(len=20), parameter pahm_global::def_ncnam_wndy = 'vwnd'
Definition at line 190 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
defv_atmpress
real(sz), parameter pahm_global::defv_atmpress = 1013.25_SZ
Definition at line 43 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
defv_bladjustfac
real(sz), parameter pahm_global::defv_bladjustfac = 0.9_SZ
Definition at line 120 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
defv_gravity
real(sz), parameter pahm_global::defv_gravity = 9.80665_SZ
Definition at line 42 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
defv_rhoair
real(sz), parameter pahm_global::defv_rhoair = 1.1478_SZ
Definition at line 45 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
defv_rhowater
real(sz), parameter pahm_global::defv_rhowater = 1000.0000
Definition at line 49 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
deg2rad
real(sz), parameter pahm_global::deg2rad = PI / 180.0_SZ
Definition at line 76 of file global.F90.
Referenced by pahm_vortex::calcintensitychange(), utilities::cpptogeo::cpptogeo_1d(), utilities::cpptogeo::cpptogeo_scalar(), utilities::geotocpp::geotocpp_1d(), utilities::geotocpp::geotocpp_scalar(), parwind::gethollandfields(), pahm_vortex::newvortex(), pahm_vortex::newvortexfull(), pahm_vortex::rotate(), pahm_vortex::setvortex(), utilities::sphericaldistance::sphericaldistance_1d(), utilities::sphericaldistance::sphericaldistance_2d(), utilities::sphericaldistance::sphericaldistance_scalar(), utilities::sphericaldistanceharv(), utilities::sphericalfracpoint(), pahm_vortex::uvp(), pahm_vortex::uvpr(), pahm_vortex::uvtrans(), and pahm_vortex::uvtranspoint().
enddate
integer pahm_global::enddate = IMISSV
Definition at line 154 of file global.F90.
enddatespecified
logical pahm_global::enddatespecified = .FALSE.
Definition at line 162 of file global.F90.
Referenced by utilities::printmodelparams().
enddatetime
character(len=64) pahm_global::enddatetime = BLANK
Definition at line 153 of file global.F90.
Referenced by utilities::printmodelparams().
endday
integer pahm_global::endday = 0
Definition at line 158 of file global.F90.
Referenced by utilities::printmodelparams().
endhour
integer pahm_global::endhour = 0
Definition at line 159 of file global.F90.
Referenced by utilities::printmodelparams().
endmin
integer pahm_global::endmin = 0
Definition at line 160 of file global.F90.
Referenced by utilities::printmodelparams().
endmonth
integer pahm_global::endmonth = 0
Definition at line 157 of file global.F90.
Referenced by utilities::printmodelparams().
endsec
integer pahm_global::endsec = 0
Definition at line 161 of file global.F90.
Referenced by utilities::printmodelparams().
endsimspecified
logical pahm_global::endsimspecified = .FALSE.
Definition at line 168 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
endsimtime
real(sz) pahm_global::endsimtime = RMISSV
Definition at line 166 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
endtime
integer pahm_global::endtime = IMISSV
Definition at line 155 of file global.F90.
endyear
integer pahm_global::endyear = IMISSV
Definition at line 156 of file global.F90.
Referenced by utilities::printmodelparams().
gravity
real(sz) pahm_global::gravity = DEFV_GRAVITY
Definition at line 114 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
kt2ms
real(sz), parameter pahm_global::kt2ms = NM2M / 3600.0_SZ
Definition at line 83 of file global.F90.
Referenced by pahm_vortex::calcrmaxesfull(), pahm_vortex::newvortex(), pahm_vortex::newvortexfull(), parwind::processhollanddata(), pahm_vortex::uvp(), pahm_vortex::uvpr(), pahm_vortex::vhnocori(), pahm_vortex::vhwithcori(), and pahm_vortex::vhwithcorifull().
logfilename
character(len=fnamelen) pahm_global::logfilename = TRIM(ADJUSTL(PROG_NAME_LOW)) // '_model.log'
Definition at line 96 of file global.F90.
Referenced by pahm_messages::openlogfile().
lun_btrk
integer, parameter pahm_global::lun_btrk = 22
Definition at line 30 of file global.F90.
Referenced by parwind::gethollandfields(), csv_module::initialize_csv_file(), parwind::readbesttrackfile(), and parwind::writebesttrackdata().
lun_btrk1
integer, parameter pahm_global::lun_btrk1 = 23
Definition at line 31 of file global.F90.
Referenced by parwind::gethollandfields(), parwind::readbesttrackfile(), and parwind::writebesttrackdata().
lun_ctrl
integer, parameter pahm_global::lun_ctrl = 10
Definition at line 26 of file global.F90.
Referenced by utilities::readcontrolfile().
lun_inp
integer, parameter pahm_global::lun_inp = 14
Definition at line 27 of file global.F90.
Referenced by pahm_mesh::readmeshasciifort14().
lun_inp1
integer, parameter pahm_global::lun_inp1 = 15
Definition at line 28 of file global.F90.
lun_log
integer, parameter pahm_global::lun_log = 35
Definition at line 29 of file global.F90.
Referenced by pahm_messages::closelogfile(), pahm_messages::logmessage::logmessage_1(), pahm_messages::logmessage::logmessage_2(), and pahm_messages::openlogfile().
lun_out
integer, parameter pahm_global::lun_out = 25
Definition at line 32 of file global.F90.
lun_out1
integer, parameter pahm_global::lun_out1 = 26
Definition at line 33 of file global.F90.
lun_screen
integer, parameter pahm_global::lun_screen = 6
Definition at line 25 of file global.F90.
Referenced by pahm_messages::programhelp(), pahm_messages::programversion(), utilities::readcontrolfile(), pahm_messages::screenmessage::screenmessage_1(), and pahm_messages::screenmessage::screenmessage_2().
m2nm
real(sz), parameter pahm_global::m2nm = 1.0_SZ / NM2M
Definition at line 82 of file global.F90.
Referenced by pahm_vortex::uvp().
mb2kpa
real(sz), parameter pahm_global::mb2kpa = 0.1_SZ
Definition at line 87 of file global.F90.
Referenced by parwind::gethollandfields().
mb2pa
real(sz), parameter pahm_global::mb2pa = 100.0_SZ
Definition at line 86 of file global.F90.
Referenced by pahm_vortex::calcrmaxesfull(), parwind::gethollandfields(), pahm_vortex::newvortex(), pahm_vortex::newvortexfull(), pahm_vortex::uvp(), and pahm_vortex::uvpr().
mdbegsimtime
real(sz) pahm_global::mdbegsimtime = RMISSV
Definition at line 178 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
mdendsimtime
real(sz) pahm_global::mdendsimtime = RMISSV
Definition at line 179 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
mdoutdt
real(sz) pahm_global::mdoutdt = RMISSV
Definition at line 177 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
meshfileform
character(len=64) pahm_global::meshfileform = BLANK
Definition at line 104 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), utilities::printmodelparams(), and pahm_mesh::readmesh().
meshfilename
character(len=fnamelen) pahm_global::meshfilename = BLANK
Definition at line 102 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), utilities::printmodelparams(), pahm_mesh::readmesh(), and pahm_mesh::readmeshasciifort14().
meshfilenamespecified
logical pahm_global::meshfilenamespecified = .FALSE.
Definition at line 101 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and pahm_mesh::readmesh().
meshfiletype
character(len=64) pahm_global::meshfiletype = BLANK
Definition at line 103 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), utilities::printmodelparams(), and pahm_mesh::readmesh().
modeltype
integer pahm_global::modeltype = IMISSV
Definition at line 198 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_drivermod::pahm_run(), and utilities::printmodelparams().
ms2kt
real(sz), parameter pahm_global::ms2kt = 1.0_SZ / KT2MS
Definition at line 84 of file global.F90.
Referenced by pahm_vortex::vhnocori(), pahm_vortex::vhwithcori(), and pahm_vortex::vhwithcorifull().
nbtrfiles
integer pahm_global::nbtrfiles = IMISSV
Definition at line 107 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), utilities::printmodelparams(), parwind::processhollanddata(), parwind::readbesttrackfile(), and parwind::readcsvbesttrackfile().
ncdeflate
integer pahm_global::ncdeflate = 0
Definition at line 184 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
ncdlevel
integer pahm_global::ncdlevel = 0
Definition at line 185 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
ncshuffle
integer pahm_global::ncshuffle = 0
Definition at line 183 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
ncvarnam_pres
character(len=20) pahm_global::ncvarnam_pres = DEF_NCNAM_PRES
Definition at line 194 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
ncvarnam_wndx
character(len=20) pahm_global::ncvarnam_wndx = DEF_NCNAM_WNDX
Definition at line 194 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
ncvarnam_wndy
character(len=20) pahm_global::ncvarnam_wndy = DEF_NCNAM_WNDY
Definition at line 194 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
nm2m
real(sz), parameter pahm_global::nm2m = 1852.0_SZ
Definition at line 81 of file global.F90.
Referenced by pahm_vortex::calcrmaxesfull(), parwind::processhollanddata(), pahm_vortex::uvp(), pahm_vortex::uvpr(), pahm_vortex::vhwithcori(), and pahm_vortex::vhwithcorifull().
noutdt
integer pahm_global::noutdt = IMISSV
Definition at line 176 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), pahm_drivermod::pahm_init(), and utilities::printmodelparams().
omega
real(sz), parameter pahm_global::omega = 2.0_SZ * PI / 86164.2_SZ
Definition at line 85 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_vortex::newvortex(), pahm_vortex::newvortexfull(), and pahm_vortex::setvortex().
one2ten
real(sz), parameter pahm_global::one2ten = 0.8928_SZ
Definition at line 72 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_vortex::uvp(), and pahm_vortex::uvpr().
outdt
real(sz) pahm_global::outdt = RMISSV
Definition at line 175 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
outfilename
character(len=fnamelen) pahm_global::outfilename = BLANK
Definition at line 182 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_drivermod::pahm_run(), and utilities::printmodelparams().
outfilenamespecified
logical pahm_global::outfilenamespecified = .FALSE.
Definition at line 181 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and pahm_drivermod::pahm_run().
pi
real(sz), parameter pahm_global::pi = 3.141592653589793_SZ
Definition at line 75 of file global.F90.
rad2deg
real(sz), parameter pahm_global::rad2deg = 180.0_SZ / PI
Definition at line 77 of file global.F90.
Referenced by parwind::gethollandfields(), utilities::sphericalfracpoint(), and pahm_vortex::uvp().
rearth
real(sz), parameter pahm_global::rearth = 6378206.4_SZ
Definition at line 80 of file global.F90.
Referenced by utilities::cpptogeo::cpptogeo_1d(), utilities::cpptogeo::cpptogeo_scalar(), utilities::geotocpp::geotocpp_1d(), utilities::geotocpp::geotocpp_scalar(), pahm_netcdfio::initadcircnetcdfoutfile(), utilities::sphericaldistance::sphericaldistance_1d(), utilities::sphericaldistance::sphericaldistance_2d(), utilities::sphericaldistance::sphericaldistance_scalar(), utilities::sphericaldistanceharv(), utilities::sphericalfracpoint(), and pahm_vortex::uvp().
refdate
integer pahm_global::refdate = IMISSV
Definition at line 130 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
refdatespecified
logical pahm_global::refdatespecified = .FALSE.
Definition at line 138 of file global.F90.
Referenced by utilities::printmodelparams().
refdatetime
character(len=64) pahm_global::refdatetime = BLANK
Definition at line 129 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), and utilities::printmodelparams().
refday
integer pahm_global::refday = 0
Definition at line 134 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
refhour
integer pahm_global::refhour = 0
Definition at line 135 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
refmin
integer pahm_global::refmin = 0
Definition at line 136 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
refmonth
integer pahm_global::refmonth = 0
Definition at line 133 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
refsec
integer pahm_global::refsec = 0
Definition at line 137 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
reftime
integer pahm_global::reftime = IMISSV
Definition at line 131 of file global.F90.
Referenced by utilities::checkcontrolfileinputs().
refyear
integer pahm_global::refyear = IMISSV
Definition at line 132 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), utilities::printmodelparams(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
rhoair
real(sz) pahm_global::rhoair = DEFV_RHOAIR
Definition at line 116 of file global.F90.
Referenced by pahm_vortex::calcrmaxesfull(), utilities::checkcontrolfileinputs(), parwind::gethollandfields(), pahm_vortex::newvortex(), pahm_vortex::newvortexfull(), and utilities::printmodelparams().
rhowater
real(sz) pahm_global::rhowater = DEFV_RHOWATER
Definition at line 115 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), parwind::gethollandfields(), and utilities::printmodelparams().
ten2one
real(sz), parameter pahm_global::ten2one = 1.0_SZ / 0.8928_SZ
Definition at line 73 of file global.F90.
times
real(sz), dimension(:), allocatable pahm_global::times
Definition at line 217 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), and pahm_drivermod::pahm_run().
title
character(len=512) pahm_global::title = BLANK
Definition at line 112 of file global.F90.
Referenced by pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
unittime
character(len=1) pahm_global::unittime = 'S'
Definition at line 170 of file global.F90.
Referenced by utilities::checkcontrolfileinputs(), pahm_netcdfio::initadcircnetcdfoutfile(), and utilities::printmodelparams().
windreduction
real(sz) pahm_global::windreduction = DEFV_BLADJUSTFAC
Definition at line 121 of file global.F90.
Referenced by pahm_vortex::uvp(), and pahm_vortex::uvpr().
wpress
real(sz), dimension(:), allocatable pahm_global::wpress
Definition at line 216 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), pahm_drivermod::pahm_run(), and pahm_netcdfio::writenetcdfrecord().
writeparams
logical pahm_global::writeparams = .FALSE.
Definition at line 205 of file global.F90.
Referenced by utilities::printmodelparams().
wvelx
real(sz), dimension(:), allocatable pahm_global::wvelx
Definition at line 216 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), pahm_drivermod::pahm_run(), and pahm_netcdfio::writenetcdfrecord().
wvely
real(sz), dimension(:), allocatable pahm_global::wvely
Definition at line 216 of file global.F90.
Referenced by parwind::gethollandfields(), pahm_netcdfio::initadcircnetcdfoutfile(), pahm_drivermod::pahm_run(), and pahm_netcdfio::writenetcdfrecord().