PaHM: utilities Module Reference
utilities Module Reference
Data Types
interface cpptogeo
interface geotocpp
interface sphericaldistance
Functions/Subroutines
subroutine openfileforread (lun, fileName, errorIO)
This subroutine opens an existing file for reading.
subroutine readcontrolfile (inpFile)
This subroutine reads the program's main control file.
subroutine printmodelparams ()
This subroutine prints on the screen the values of the program's parameters.
integer function getlinerecord (inpLine, outLine, lastCommFlag)
Gets a line from a file.
integer function parseline (inpLine, outLine, keyWord, nVal, cVal, rVal)
This function parses lines of text from input script/control files.
integer function checkcontrolfileinputs ()
Checks the user defined control file inputs.
integer function loadintvar (nInp, vInp, nOut, vOut)
This function loads input values into a requested model integer variable.
integer function loadlogvar (nInp, vInp, nOut, vOut)
This function loads input values into a requested model logical variable.
integer function loadrealvar (nInp, vInp, nOut, vOut)
This function loads input values into a requested model real variable.
pure character(len(inpstring)) function tolowercase (inpString)
Convert a string to lower-case.
pure character(len(inpstring)) function touppercase (inpString)
Convert a string to upper-case.
real(sz) function convlon (inpLon)
Convert longitude values from the (0, 360) to the (-180, 180) notation.
subroutine geotocpp_scalar (lat, lon, lat0, lon0, x, y)
Transform from geographical (lon, lat) coordinates into CPP (x, y) coordinates.
subroutine geotocpp_1d (lat, lon, lat0, lon0, x, y)
Transform from geographical (lon, lat) coordinates into CPP (x, y) coordinates.
subroutine cpptogeo_scalar (x, y, lat0, lon0, lat, lon)
Transform from CPP (x, y) coordinates into geographical (lon, lat) coordinates.
subroutine cpptogeo_1d (x, y, lat0, lon0, lat, lon)
Transform from CPP (x, y) coordinates into geographical (lon, lat) coordinates.
real(sz) function sphericaldistance_scalar (lat1, lon1, lat2, lon2)
Calculates the distance of two points along the great circle using the Vincenty formula.
real(sz) function, dimension(:), allocatable sphericaldistance_1d (lats, lons, lat0, lon0)
Calculates the distance of points along the great circle using the Vincenty formula.
real(sz) function, dimension(:, :), allocatable sphericaldistance_2d (lats, lons, lat0, lon0)
Calculates the distance of points along the great circle using the Vincenty formula.
real(sz) function sphericaldistanceharv (lat1, lon1, lat2, lon2)
Calculates the distance of two points along the great circle using the Haversine formula.
subroutine sphericalfracpoint (lat1, lon1, lat2, lon2, fraction, latf, lonf, distf, dist12)
Calculates the coordinates of an intermediate point between two points along the great circle.
subroutine getlocandratio (val, arrVal, idx1, idx2, wtRatio)
Calculates the location of a value in an 1D array of values.
integer function charunique (inpVec, outVec, idxVec)
Find the unique non-blank elements in 1D character array.
real(sp) function valstr (String)
Returns the value of the leading double precision real numeric string.
real(hp) function dvalstr (String)
Returns the value of the leading double precision real numeric string.
integer function intvalstr (String)
Returns the value of the leading integer numeric string.
integer function realscan (String, Pos, Value)
Scans string looking for the leading single precision real numeric string.
integer function drealscan (String, Pos, Value)
Scans string looking for the leading double precision real numeric string.
integer function intscan (String, Pos, Signed, Value)
Scans string looking for the leading integer numeric string.
Variables
real(sz), parameter closetol = 0.001_SZ
Function/Subroutine Documentation
charunique()
integer function utilities::charunique (character(len=*), dimension(:), intent(in) inpVec, character(len=*), dimension(:), intent(out) outVec, integer, dimension(:), intent(out), allocatable idxVec)
Find the unique non-blank elements in 1D character array.
Parameters
inpVec The input 1D string array
outVec The output 1D string array of the unique elements (output)
idxVec The 1D array of indexes of the unique elements in the inpVec array (output)
Returns
myRec: The number of the uniques elements in the input array
Definition at line 2576 of file utilities.F90.
Referenced by parwind::processhollanddata(), parwind::readbesttrackfile(), and parwind::readcsvbesttrackfile().
checkcontrolfileinputs()
integer function utilities::checkcontrolfileinputs
Checks the user defined control file inputs.
The purpose of this subroutine is to process the input parameters and check if the user supplied values in the control file are valid entries. If a value for an input parameter is not supplied, then a default value is assigned to that parameter. If the parameter doesn't have a default value, it is then a mandatory parameter that the user needs to supply a valid value.
Returns
myStatus: The error status, no error: status = 0
Definition at line 1140 of file utilities.F90.
References pahm_global::backgroundatmpress, pahm_global::begsimspecified, pahm_global::begsimtime, pahm_global::besttrackfilename, pahm_global::besttrackfilenamespecified, pahm_global::bladjustfac, closetol, pahm_global::def_ncnam_pres, pahm_global::def_ncnam_wndx, pahm_global::def_ncnam_wndy, pahm_global::defv_atmpress, pahm_global::defv_bladjustfac, pahm_global::defv_gravity, pahm_global::defv_rhoair, pahm_global::defv_rhowater, pahm_global::endsimspecified, pahm_global::endsimtime, timedateutils::firstgregdate, timedateutils::firstgregtime, timedateutils::gettimeconvsec(), pahm_global::gravity, timedateutils::joindate(), pahm_global::mdbegsimtime, pahm_global::mdendsimtime, pahm_global::mdoutdt, pahm_global::meshfileform, pahm_global::meshfilename, pahm_global::meshfilenamespecified, pahm_global::meshfiletype, pahm_global::modeltype, pahm_global::nbtrfiles, pahm_global::ncdeflate, pahm_global::ncdlevel, pahm_global::ncshuffle, pahm_global::ncvarnam_pres, pahm_global::ncvarnam_wndx, pahm_global::ncvarnam_wndy, pahm_global::noutdt, pahm_global::outdt, pahm_global::outfilename, pahm_global::outfilenamespecified, pahm_global::refdate, pahm_global::refdatetime, pahm_global::reftime, pahm_global::rhoair, pahm_global::rhowater, touppercase(), and pahm_global::unittime.
Referenced by readcontrolfile().
convlon()
real(sz) function utilities::convlon (real(sz) inpLon)
Convert longitude values from the (0, 360) to the (-180, 180) notation.
Parameters
inpLon The longitude value to be converted
Returns
myValOut: The converted longitude value
Definition at line 1760 of file utilities.F90.
cpptogeo_1d()
subroutine utilities::cpptogeo_1d (real(sz), dimension(:), intent(in) x, real(sz), dimension(:), intent(in) y, real(sz), intent(in) lat0, real(sz), intent(in) lon0, real(sz), dimension(:), intent(out) lat, real(sz), dimension(:), intent(out) lon)
Transform from CPP (x, y) coordinates into geographical (lon, lat) coordinates.
Transforms 1D CPP coordinates into 1D geographical coordinates. This is the Equidistant Cylindrical projection, also called equirectangular projection, equidirectional projection, geographic projection, plate carree or carte parallelogrammatique projection.
Parameters
x X coordinate: x (m) - real, 1D array
y Y coordinate: y (m) - real, 1D array
lat0 Latitude of projection origin (degrees north) - real, scalar
lon0 Longitude of projection origin (degrees east) - real, scalar
lat Latitude (degrees north) - real, 1D array (output)
lon Longitude (degrees east) - real, 1D array (output)
Definition at line 1940 of file utilities.F90.
cpptogeo_scalar()
subroutine utilities::cpptogeo_scalar (real(sz), intent(in) x, real(sz), intent(in) y, real(sz), intent(in) lat0, real(sz), intent(in) lon0, real(sz), intent(out) lat, real(sz), intent(out) lon)
Transform from CPP (x, y) coordinates into geographical (lon, lat) coordinates.
This is the Equidistant Cylindrical projection, also called equirectangular projection, equidirectional projection, geographic projection, plate carree or carte parallelogrammatique projection.
Parameters
x X coordinate: x (m) - real, scalar
y Y coordinate: y (m) - real, scalar
lat0 Latitude of projection origin (degrees north) - real, scalar
lon0 Longitude of projection origin (degrees east) - real, scalar
lat Latitude (degrees north) - real, scalar (output)
lon Longitude (degrees east) - real, scalar (output)
Definition at line 1893 of file utilities.F90.
drealscan()
integer function utilities::drealscan (character(len=*), intent(in) String, integer, intent(in) Pos, real(hp), intent(out) Value)
Scans string looking for the leading double precision real numeric string.
Scanning begins at the position specified by pos and continues to the end of the string. Leading blanks are ignored.
   The numeric string must have the form:
   [sign] d+ ['.' d*] ['e' [sign] d+]        or
   [sign]     '.' d+  ['e' [sign] d+]
   where sign is '+' or '-',
   d* is zero or more digits,
   d+ is one  or more digits,
   '.' and 'e' are literal (also accept lower case 'e'),
   brackets [, ] delimit optional sequences.
   Value is set to the numeric value of the string.
   The function value is set to the position within the string where
   the numeric string ends plus one (i.e., the break character).
Parameters
String The input string
Pos The position in the input string where the scanning begins
Value The numeric value of the string
Returns
myVal: The position within the string where the numeric string ends plus one (i.e., the break character)
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 2942 of file utilities.F90.
References intscan().
Referenced by dvalstr().
dvalstr()
real(hp) function utilities::dvalstr (character(len=*), intent(in) String)
Returns the value of the leading double precision real numeric string.
Parameters
String The input string
Returns
myVal: The value of the real number in double precision as extracted from the input string
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 2684 of file utilities.F90.
References drealscan().
geotocpp_1d()
subroutine utilities::geotocpp_1d (real(sz), dimension(:), intent(in) lat, real(sz), dimension(:), intent(in) lon, real(sz), intent(in) lat0, real(sz), intent(in) lon0, real(sz), dimension(:), intent(out) x, real(sz), dimension(:), intent(out) y)
Transform from geographical (lon, lat) coordinates into CPP (x, y) coordinates.
Transforms 1D geographical coordinates into 1D CPP coordinates. This is the Equidistant Cylindrical projection, also called equirectangular projection, equidirectional projection, geographic projection, plate carree or carte parallelogrammatique projection.
Parameters
lat Latitude (degrees north) - real, 1D array
lon Longitude (degrees east) - real, 1D array
lat0 Latitude of projection origin (degrees north) - real, scalar
lon0 Longitude of projection origin (degrees east) - real, scalar
x Calculated X coordinate: x (m) - real, 1D array (output)
y Calculated Y coordinate: y (m) - real, 1D array (output)
Definition at line 1847 of file utilities.F90.
geotocpp_scalar()
subroutine utilities::geotocpp_scalar (real(sz), intent(in) lat, real(sz), intent(in) lon, real(sz), intent(in) lat0, real(sz), intent(in) lon0, real(sz), intent(out) x, real(sz), intent(out) y)
Transform from geographical (lon, lat) coordinates into CPP (x, y) coordinates.
This is the Equidistant Cylindrical projection, also called equirectangular projection, equidirectional projection, geographic projection, plate carree or carte parallelogrammatique projection.
Parameters
lat Latitude (degrees north) - real, scalar
lon Longitude (degrees east) - real, scalar
lat0 Latitude of projection origin (degrees north) - real, scalar
lon0 Longitude of projection origin (degrees east) - real, scalar
x Calculated X coordinate: x (m) - real, scalar (output)
y Calculated Y coordinate: y (m) - real, scalar (output)
Definition at line 1800 of file utilities.F90.
getlinerecord()
integer function utilities::getlinerecord (character(len=*), intent(in) inpLine, character(len=len(inpline)), intent(out) outLine, integer, optional lastCommFlag)
Gets a line from a file.
This function reads a line record, which is neither a commented or a blank line, from a file for further processing. Commented lines are those with a first character either "#" or "!".
Parameters
inpLine The input text line
lastCommFlag Optional flag to check/remove commented portion at the right of the text line
lastCommFlag <= 0 do nothing
lastCommFlag > 0 check for "#!" symbols at the right of the text line and remove that portion of the line
outLine The output line (the left adjusted input line)
Returns
myLen: The length of outLine (end blanks removed)
Definition at line 773 of file utilities.F90.
Referenced by parseline(), parwind::readbesttrackfile(), and parwind::readcsvbesttrackfile().
getlocandratio()
subroutine utilities::getlocandratio (real(sz), intent(in) val, real(sz), dimension(:), intent(in) arrVal, integer, intent(out) idx1, integer, intent(out) idx2, real(sz), intent(out) wtRatio)
Calculates the location of a value in an 1D array of values.
Determines the linear interpolation parameters given the 1D input search array arrVal and the search value val. The linear interpolation is performed using the equation: VAR(estimated) = VAR(idx1) + wtRatio * (VAR(idx2) - VAR(idx1)).
Parameters
val The value to search for, such that arrVal(idx1) <= val <= arrVal(idx2)
arrVal The one-dimensional array to search (PV ordered in ascending order?)
idx1 The index of the lowest array bound such that: arrVal(idx1) <= val (output)
idx2 The index of the highest array bound such that: arrVal(idx2) >= val (output)
wtRatio The ratio factor used in the linear interpolation calculation:
VAR(estimated) = VAR(idx1) + wtRatio * (VAR(idx2) - VAR(idx1))
where VAR is the variable to be interpolated
Definition at line 2462 of file utilities.F90.
Referenced by parwind::gethollandfields().
intscan()
integer function utilities::intscan (character(len=*), intent(in) String, integer, intent(in) Pos, logical, intent(in) Signed, integer, intent(out) Value)
Scans string looking for the leading integer numeric string.
Scanning begins at the position specified by pos and continues to the end of the string. Leading blanks are ignored.
   The search may be for a signed (signed = .true.) or unsigned
   (signed = .FALSE.) integer value.  If signed, leading plus (+) or minus (-)
   is allowed.  If unsigned, they will terminate the scan as they are
   invalid for an unsigned integer.
   Value is set to the numeric value of the string.
   The function value is set to the position within the string where
   the numeric string ends plus one (i.e., the break character).
Parameters
String The input string
Pos The position in the input string where the scanning begins
Signed The sign (+, -) of the numeric string, if present
Value The numeric value of the string
Returns
myVal: The position within the string where the numeric string ends plus one (i.e., the break character)
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 3095 of file utilities.F90.
Referenced by drealscan(), intvalstr(), and realscan().
intvalstr()
integer function utilities::intvalstr (character(len=*), intent(in) String)
Returns the value of the leading integer numeric string.
Parameters
String The input string
Returns
myVal: The value of the integer number as extracted from the input string
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 2726 of file utilities.F90.
References intscan().
Referenced by parwind::readcsvbesttrackfile().
loadintvar()
integer function utilities::loadintvar (integer, intent(in) nInp, real(sz), dimension(ninp), intent(in) vInp, integer, intent(in) nOut, integer, dimension(nout), intent(out) vOut)
This function loads input values into a requested model integer variable.
Parameters
nInp Number of input values
vInp Array of input values
nOut Number of output values
vOut Array of output values (integer, output)
Returns
nValsOut: Number of processed output values
Note
Adopted from the ROMS source (Utility/inp_par.F, load_i)
Definition at line 1478 of file utilities.F90.
Referenced by readcontrolfile().
loadlogvar()
integer function utilities::loadlogvar (integer, intent(in) nInp, character(len=*), dimension(ninp), intent(in) vInp, integer, intent(in) nOut, logical, dimension(nout), intent(out) vOut)
This function loads input values into a requested model logical variable.
Parameters
nInp Number of input values
vInp Array of input values
nOut Number of output values
vOut Array of output values (logical, output)
Returns
nValsOut: Number of processed output values
Note
Adopted from the ROMS source (Utility/inp_par.F, load_l)
Definition at line 1544 of file utilities.F90.
loadrealvar()
integer function utilities::loadrealvar (integer, intent(in) nInp, real(sz), dimension(ninp), intent(in) vInp, integer, intent(in) nOut, real(sz), dimension(nout), intent(out) vOut)
This function loads input values into a requested model real variable.
Parameters
nInp Number of input values
vInp Array of input values
nOut Number of output values
vOut Array of output values (real, output)
Returns
nValsOut: Number of processed output values
Note
Adopted from the ROMS source (Utility/inp_par.F, load_r)
Definition at line 1622 of file utilities.F90.
Referenced by readcontrolfile().
openfileforread()
subroutine utilities::openfileforread (integer, intent(in) lun, character(len=*), intent(in) fileName, integer, intent(out) errorIO)
This subroutine opens an existing file for reading.
Parameters
lun The logical unit number (LUN) to use
fileName The full pathname of the input file
errorIO The error status, no error: status = 0 (output)
Definition at line 68 of file utilities.F90.
References pahm_messages::error, pahm_messages::info, pahm_messages::scratchmessage, pahm_messages::setmessagesource(), and pahm_messages::unsetmessagesource().
Referenced by csv_module::initialize_csv_file(), parwind::readbesttrackfile(), parwind::readcsvbesttrackfile(), and pahm_mesh::readmeshasciifort14().
parseline()
integer function utilities::parseline (character(len=*), intent(in) inpLine, character(len=len(inpline)), intent(out) outLine, character(len=40), intent(inout) keyWord, integer, intent(inout) nVal, character(len=512), dimension(200), intent(inout) cVal, real(sz), dimension(200), intent(inout) rVal)
This function parses lines of text from input script/control files.
It processes each uncommented or non-blank line in the file to extract the settings for the program's variables. It is called repeatedly from ReadControlFile that sets all required program variables.
Parameters
inpLine The input text line
outLine The output line, left adjusted input line (output)
keyWord The keyword to extract settings for (input/output)
nVal The number of values provided for the keyword (input/output)
cVal String array (cVal(nVal)) that holds the string values provided for the keyword (input/output)
rVal Real array (rVal(nVal)) that holds the values provided for the keyword (input/output)
Returns
myStatus: The error status, no error: status = 0
Note
Adopted from the ROMS source (Utility/inp_par.F, decode_line)
Definition at line 869 of file utilities.F90.
References getlinerecord(), and touppercase().
Referenced by readcontrolfile().
printmodelparams()
subroutine utilities::printmodelparams
This subroutine prints on the screen the values of the program's parameters.
Definition at line 644 of file utilities.F90.
References pahm_global::backgroundatmpress, pahm_global::begdatespecified, pahm_global::begdatetime, pahm_global::begday, pahm_global::beghour, pahm_global::begmin, pahm_global::begmonth, pahm_global::begsec, pahm_global::begsimspecified, pahm_global::begsimtime, pahm_global::begyear, pahm_global::besttrackfilename, pahm_global::bladjustfac, pahm_global::enddatespecified, pahm_global::enddatetime, pahm_global::endday, pahm_global::endhour, pahm_global::endmin, pahm_global::endmonth, pahm_global::endsec, pahm_global::endsimspecified, pahm_global::endsimtime, pahm_global::endyear, pahm_global::gravity, pahm_global::mdbegsimtime, pahm_global::mdendsimtime, pahm_global::mdoutdt, pahm_global::meshfileform, pahm_global::meshfilename, pahm_global::meshfiletype, pahm_global::modeltype, pahm_global::nbtrfiles, pahm_global::ncdeflate, pahm_global::ncdlevel, pahm_global::ncshuffle, pahm_global::ncvarnam_pres, pahm_global::ncvarnam_wndx, pahm_global::ncvarnam_wndy, pahm_global::noutdt, pahm_global::outdt, pahm_global::outfilename, pahm_global::refdatespecified, pahm_global::refdatetime, pahm_global::refday, pahm_global::refhour, pahm_global::refmin, pahm_global::refmonth, pahm_global::refsec, pahm_global::refyear, pahm_global::rhoair, pahm_global::rhowater, pahm_global::title, tolowercase(), pahm_global::unittime, and pahm_global::writeparams.
Referenced by readcontrolfile().
readcontrolfile()
subroutine utilities::readcontrolfile (character(len=*), intent(in) inpFile)
This subroutine reads the program's main control file.
Reads the control file of the program and it is repeatedly calling GetLineRecord to process each line in the file. Upon successful processing of the line, it sets the relevant program parameters and variables. This subroutine is called first as it is required by the subsequent model run.
The control file (default filename pahm_control.in) contains all required settings (user configured) required to run the program. Most of the settings have default values, in case the user hasn't supplied a value.
Parameters
inpFile The full pathname of the input file
Definition at line 153 of file utilities.F90.
References pahm_sizes::blank, checkcontrolfileinputs(), closetol, timedateutils::datetime2string(), timedateutils::gettimeconvsec(), pahm_sizes::imissv, timedateutils::joindate(), timedateutils::juldaytogreg(), loadintvar(), loadrealvar(), pahm_global::lun_ctrl, pahm_global::lun_screen, parseline(), printmodelparams(), pahm_messages::setmessagesource(), and touppercase().
Referenced by pahm_drivermod::getprogramcmdlargs().
realscan()
integer function utilities::realscan (character(len=*), intent(in) String, integer, intent(in) Pos, real(sp), intent(out) Value)
Scans string looking for the leading single precision real numeric string.
Scanning begins at the position specified by pos and continues to the end of the string. Leading blanks are ignored.
   The numeric string must have the form:
   [sign] d+ ['.' d*] ['e' [sign] d+]        or
   [sign]     '.' d+  ['e' [sign] d+]
   where sign is '+' or '-',
   d* is zero or more digits,
   d+ is one  or more digits,
   '.' and 'e' are literal (also accept lower case 'e'),
   brackets [, ] delimit optional sequences.
   Value is set to the numeric value of the string.
   The function value is set to the position within the string where
   the numeric string ends plus one (i.e., the break character).
Parameters
String The input string
Pos The position in the input string where the scanning begins
Value The numeric value of the string
Returns
myVal: The position within the string where the numeric string ends plus one (i.e., the break character)
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 2788 of file utilities.F90.
References intscan().
Referenced by valstr().
sphericaldistance_1d()
real(sz) function, dimension(:), allocatable utilities::sphericaldistance_1d (real(sz), dimension(:), intent(in) lats, real(sz), dimension(:), intent(in) lons, real(sz), intent(in) lat0, real(sz), intent(in) lon0)
Calculates the distance of points along the great circle using the Vincenty formula.
Function to get the great-circle distance along the surface of a sphere (the earth's surface in this case). Compute the great-circle distance using the Vincenty formula for distance along a sphere.
See also
https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulas
https://en.wikipedia.org/wiki/Vincenty's_formulae
Vincenty, Thaddeus (April 1975a). "Direct and Inverse Solutions of Geodesics \n on the Ellipsoid with application of nested equations".
Survey Review. XXIII (176): 88-93. doi:10.1179/sre.1975.23.176.88.
Vincenty, Thaddeus (August 1975b). Geodetic inverse solution between antipodal points
(Technical report). DMAAC Geodetic Survey Squadron. doi:10.5281/zenodo.32999.
Parameters
lats Latitude of first points - real, 1D array
lons Longitude of first points - real, 1D array
lat0 Latitude of second point - real, scalar
lon0 Longitude of second point - real, scalar
Returns
myValOut: The great-circle distance in meters, 1D array
Definition at line 2061 of file utilities.F90.
sphericaldistance_2d()
real(sz) function, dimension(:, :), allocatable utilities::sphericaldistance_2d (real(sz), dimension(:, :), intent(in) lats, real(sz), dimension(:, :), intent(in) lons, real(sz), intent(in) lat0, real(sz), intent(in) lon0)
Calculates the distance of points along the great circle using the Vincenty formula.
Function to get the great-circle distance along the surface of a sphere (the earth's surface in this case). Compute the great-circle distance using the Vincenty formula for distance along a sphere.
See also
https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulas
https://en.wikipedia.org/wiki/Vincenty's_formulae
Vincenty, Thaddeus (April 1975a). "Direct and Inverse Solutions of Geodesics \n on the Ellipsoid with application of nested equations".
Survey Review. XXIII (176): 88-93. doi:10.1179/sre.1975.23.176.88.
Vincenty, Thaddeus (August 1975b). Geodetic inverse solution between antipodal points
(Technical report). DMAAC Geodetic Survey Squadron. doi:10.5281/zenodo.32999.
Parameters
lats Latitude of first points - real, 2D array
lons Longitude of first points - real, 2D array
lat0 Latitude of second point - real, scalar
lon0 Longitude of second point - real, scalar
Returns
myValOut: The great-circle distance in meters, 2D array
Definition at line 2160 of file utilities.F90.
sphericaldistance_scalar()
real(sz) function utilities::sphericaldistance_scalar (real(sz), intent(in) lat1, real(sz), intent(in) lon1, real(sz), intent(in) lat2, real(sz), intent(in) lon2)
Calculates the distance of two points along the great circle using the Vincenty formula.
Function to get the great-circle distance along the surface of a sphere (the earth's surface in this case). Compute the great-circle distance using the Vincenty formula for distance along a sphere.
See also
https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulas
https://en.wikipedia.org/wiki/Vincenty's_formulae
Vincenty, Thaddeus (April 1975a). "Direct and Inverse Solutions of Geodesics \n on the Ellipsoid with application of nested equations".
Survey Review. XXIII (176): 88-93. doi:10.1179/sre.1975.23.176.88.
Vincenty, Thaddeus (August 1975b). Geodetic inverse solution between antipodal points
(Technical report). DMAAC Geodetic Survey Squadron. doi:10.5281/zenodo.32999.
Parameters
lat1 Latitude of first point - real, scalar
lon1 Longitude of first point - real, scalar
lat2 Latitude of second point - real, scalar
lon2 Longitude of second point - real, scalar
Returns
myValOut: The great-circle distance in meters
Definition at line 1993 of file utilities.F90.
sphericaldistanceharv()
real(sz) function utilities::sphericaldistanceharv (real(sz), intent(in) lat1, real(sz), intent(in) lon1, real(sz), intent(in) lat2, real(sz), intent(in) lon2)
Calculates the distance of two points along the great circle using the Haversine formula.
Function to get the great-circle distance along the surface of a sphere (the earth's surface in this case). Compute the great-circle distance using the Haversine formula for distance along a sphere.
See also
https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulas
https://en.wikipedia.org/wiki/Haversine_formula
van Brummelen, Glen Robert (2013). Heavenly Mathematics: The Forgotten Art
of Spherical Trigonometry. Princeton University Press. ISBN 9780691148922.0691148929.
Parameters
lat1 Latitude of first point - real, scalar
lon1 Longitude of first point - real, scalar
lat2 Latitude of second point - real, scalar
lon2 Longitude of second point - real, scalar
Returns
myValOut: The great-circle distance in meters
Definition at line 2261 of file utilities.F90.
References pahm_global::deg2rad, and pahm_global::rearth.
sphericalfracpoint()
subroutine utilities::sphericalfracpoint (real(sz), intent(in) lat1, real(sz), intent(in) lon1, real(sz), intent(in) lat2, real(sz), intent(in) lon2, real(sz), intent(in) fraction, real(sz), intent(out) latf, real(sz), intent(out) lonf, real(sz), intent(out), optional distf, real(sz), intent(out), optional dist12)
Calculates the coordinates of an intermediate point between two points along the great circle.
Calculates the latitude and longitude of an intermediate point at any fraction that lies between two points along their great circle path. Compute the great-circle distance using the Haversine formula for distance along a sphere.
See also
https://en.wikipedia.org/wiki/Great-circle_distance#Computational_formulas
http://www.movable-type.co.uk/scripts/latlong.html
Parameters
lat1 Latitude of the first point (degrees north)
lon1 Longitude of the first point (degrees east)
lat2 Latitude of the second point (degrees north)
lon2 Longitude of the second point (degrees east)
fraction The fraction of the distance between points 1 and 2
where the intemediate point is located (0 <= fraction <= 1)
latf The caclulated latitude of the intermidiate point (degrees north, output)
lonf The caclulated longitude of the intermidiate point (degrees east, output)
distf The great circle distance between the first and the intermediate point (m, output)
dist12 The great circle distance between the first and the second point (m, output)
Definition at line 2364 of file utilities.F90.
References pahm_global::deg2rad, pahm_global::rad2deg, and pahm_global::rearth.
Referenced by parwind::gethollandfields().
tolowercase()
pure character(len(inpstring)) function utilities::tolowercase (character(*), intent(in) inpString)
Convert a string to lower-case.
Parameters
inpString The input string
Returns
outString: The ouput string in lower case
Definition at line 1680 of file utilities.F90.
Referenced by csv_module::initialize_csv_file(), and printmodelparams().
touppercase()
pure character(len(inpstring)) function utilities::touppercase (character(*), intent(in) inpString)
Convert a string to upper-case.
Parameters
inpString The input string
Returns
outString: The ouput string in upper case
Definition at line 1720 of file utilities.F90.
Referenced by checkcontrolfileinputs(), parseline(), parwind::processhollanddata(), parwind::readbesttrackfile(), readcontrolfile(), parwind::readcsvbesttrackfile(), pahm_mesh::readmesh(), and sortutils::stringlexcomp().
valstr()
real(sp) function utilities::valstr (character(len=*), intent(in) String)
Returns the value of the leading double precision real numeric string.
Parameters
String The input string
Returns
myVal: The value of the double precision real number as extracted from the input string
Author
C. L. Dunford - November 19, 2003
NSDFLIB, FORTRAN UTILITY SUBROUTINE PACKAGE
See also
https://www-nds.iaea.org/workshops/smr1939/Codes/ENSDF_Codes/mswindows/nsdflib/nsdflib95/nsdflib95_win.html
Definition at line 2642 of file utilities.F90.
References realscan().
Variable Documentation
closetol
real(sz), parameter utilities::closetol = 0.001_SZ
Definition at line 24 of file utilities.F90.
Referenced by checkcontrolfileinputs(), and readcontrolfile().