PaHM: pahm_sizes Module Reference
pahm_sizes Module Reference
Data Types
interface comparereals
interface fixnearwholereal
Functions/Subroutines
integer function comparedoublereals (rVal1, rVal2, eps)
Compares two double precision numbers.
integer function comparesinglereals (rVal1, rVal2, eps)
Compares two single precision numbers.
real(hp) function fixnearwholedoublereal (rVal, eps)
Rounds a double precision real number to its nearest whole number.
real(sp) function fixnearwholesinglereal (rVal, eps)
Rounds a single precision real number to its nearest whole number.
Variables
integer, parameter sp = SELECTED_REAL_KIND(6, 37)
integer, parameter hp = SELECTED_REAL_KIND(15, 307)
integer, parameter int16 = SELECTED_INT_KIND(38)
integer, parameter int8 = SELECTED_INT_KIND(18)
integer, parameter int4 = SELECTED_INT_KIND(9)
integer, parameter int2 = SELECTED_INT_KIND(4)
integer, parameter int1 = SELECTED_INT_KIND(2)
integer, parameter long = INT8
integer, parameter llong = INT16
integer, parameter wp = HP
integer, parameter ip = INT8
integer, parameter sz = HP
integer, parameter nbyte = 8
real(sz), parameter rmissv = -999999.0_SZ
integer, parameter imissv = -999999
character(len=1), parameter blank = ' '
integer, parameter fnamelen = 1024
Function/Subroutine Documentation
comparedoublereals()
integer function pahm_sizes::comparedoublereals (real(hp), intent(in) rVal1, real(hp), intent(in) rVal2, real(hp), intent(in), optional eps)
Compares two double precision numbers.
Allow users to define the value of eps. If not, eps equals to the default machine eps.
Parameters
rVal1 The first value (double precision number) in the comparison
rVal2 The second value (double precision number) in the comparison
eps The tolerance (optional) for the comparison
Returns
myValOut
   -1 (if rVal1 < rVal2)
    0 (if rVal1 = rVal2)
   +1 (if rVal1 > rVal2)
Note
The code was adopted from the D-Flow FM source (...src/precision_basics.F90)
Definition at line 101 of file sizes.F90.
comparesinglereals()
integer function pahm_sizes::comparesinglereals (real(sp), intent(in) rVal1, real(sp), intent(in) rVal2, real(sp), intent(in), optional eps)
Compares two single precision numbers.
Allow users to define the value of eps. If not, eps equals to the default machine eps.
Parameters
rVal1 The first value (single precision number) in the comparison
rVal2 The second value (single precision number) in the comparison
eps The tolerance (optional) for the comparison
Returns
myValOut
   -1 (if rVal1 < rVal2)
    0 (if rVal1 = rVal2)
   +1 (if rVal1 > rVal2)
Note
The code was adopted from the D-Flow FM source (...src/precision_basics.F90)
Definition at line 168 of file sizes.F90.
fixnearwholedoublereal()
real(hp) function pahm_sizes::fixnearwholedoublereal (real(hp), intent(in) rVal, real(hp), intent(in), optional eps)
Rounds a double precision real number to its nearest whole number.
Rounds a double precision real number to its nearest whole number. If the real number is very close (within a tolerance) to its nearest whole number then it is set equal to its nearest whole number. Allow users to define the value of the tolerance "eps". If not, then eps equals to the default machine eps.
Parameters
rVal The real number value (double precision) in the comparison
eps The tolerance (optional) for the comparison
Returns
myValOut : Either rVal or its nearest integer iVar converted to double
   rVal (if abs(rVal - iVal) >  eps
   iVal (if abs(rVal - iVal) <= eps
Definition at line 235 of file sizes.F90.
fixnearwholesinglereal()
real(sp) function pahm_sizes::fixnearwholesinglereal (real(sp), intent(in) rVal, real(sp), intent(in), optional eps)
Rounds a single precision real number to its nearest whole number.
Rounds a single precision real number to its nearest whole number. If the real number is very close (within a tolerance) to its nearest whole number then it is set equal to its nearest whole number. Allow users to define the value of the tolerance "eps". If not, then eps equals to the default machine eps.
Parameters
rVal The real number value (single precision) in the comparison
eps The tolerance (optional) for the comparison
Returns
myValOut : Either rVal or its nearest integer iVar converted to real
   rVal (if abs(rVal - iVal) >  eps
   iVal (if abs(rVal - iVal) <= eps
Definition at line 291 of file sizes.F90.
Variable Documentation
blank
character(len=1), parameter pahm_sizes::blank = ' '
Definition at line 66 of file sizes.F90.
Referenced by utilities::readcontrolfile().
fnamelen
integer, parameter pahm_sizes::fnamelen = 1024
Definition at line 69 of file sizes.F90.
hp
integer, parameter pahm_sizes::hp = SELECTED_REAL_KIND(15, 307)
Definition at line 35 of file sizes.F90.
Referenced by timedateutils::gregtojulday::gregtojuldayisec().
imissv
integer, parameter pahm_sizes::imissv = -999999
Definition at line 64 of file sizes.F90.
Referenced by timedateutils::dayofyear(), pahm_netcdfio::initadcircnetcdfoutfile(), timedateutils::monthdays(), and utilities::readcontrolfile().
int1
integer, parameter pahm_sizes::int1 = SELECTED_INT_KIND(2)
Definition at line 42 of file sizes.F90.
int16
integer, parameter pahm_sizes::int16 = SELECTED_INT_KIND(38)
Definition at line 38 of file sizes.F90.
int2
integer, parameter pahm_sizes::int2 = SELECTED_INT_KIND(4)
Definition at line 41 of file sizes.F90.
int4
integer, parameter pahm_sizes::int4 = SELECTED_INT_KIND(9)
Definition at line 40 of file sizes.F90.
int8
integer, parameter pahm_sizes::int8 = SELECTED_INT_KIND(18)
Definition at line 39 of file sizes.F90.
ip
integer, parameter pahm_sizes::ip = INT8
Definition at line 47 of file sizes.F90.
Referenced by csv_utilities::sort_ascending().
llong
integer, parameter pahm_sizes::llong = INT16
Definition at line 44 of file sizes.F90.
long
integer, parameter pahm_sizes::long = INT8
Definition at line 43 of file sizes.F90.
nbyte
integer, parameter pahm_sizes::nbyte = 8
Definition at line 57 of file sizes.F90.
rmissv
real(sz), parameter pahm_sizes::rmissv = -999999.0_SZ
Definition at line 63 of file sizes.F90.
Referenced by timedateutils::dayofyear(), timedateutils::gregtojulday::gregtojuldayisec(), pahm_netcdfio::initadcircnetcdfoutfile(), timedateutils::timeconv::timeconvisec(), and timedateutils::timeconv::timeconvrsec().
sp
integer, parameter pahm_sizes::sp = SELECTED_REAL_KIND(6, 37)
Definition at line 34 of file sizes.F90.
sz
integer, parameter pahm_sizes::sz = HP
Definition at line 56 of file sizes.F90.
wp
integer, parameter pahm_sizes::wp = HP
Definition at line 46 of file sizes.F90.
Referenced by csv_module::initialize_csv_file().